### ISSUE TITLE
Design: How to automatically track resources so clean-up is automatic, effortless?

### ISSUE THREAD

**Issue by sam-falvo** [rackerlabs/otter#1007]

**Comment by radix** [comment]
Couple of ideas:

- The `testresources` library tries to address this pretty thoroughly, but I don't know how well it works with trial. There have been issues in the past with their integration.
- The `addCleanup` method of TestCase is really useful, since it allows you to allocate a resource and set up its cleanup in the same place (and at the same time).

In the past I've implemented a system where I'll have a base class (which itself subclasses TestCase) that supports a "fixtures = [...]" list, where each fixture is some class that knows how to set up a resource and tear it down. Then each class just enumerates the fixtures it needs.

**Comment by cyli** [comment]
@radix:  From what I was told last PyCon by one of the authors, it has its own test runner and doesn't work with trial, although he said it shouldn't be hard to contribute that to testresources.  @glyph also mentioned that it doesn't work well for parallel test runs?

**Comment by glyph** [comment]
The last I spoke to lifeless about it, its design was just fundamentally opposed to working with `Deferred` or `Future` or `Effect` or anything similar, because it's a composite pattern on `TestCase`, and he wasn't willing to sacrifice full compatibility with `unittest`'s architecture, even just to add an optional dependency.  (There's also a bit of an architectural issue with trial that there aren't good hooks to expose the gross way it runs the reactor, since we keep wanting to get rid of that and make it properly *leave* the reactor running between test cases; test resources really cares about what happens between cases.)

**Comment by sam-falvo** [comment]
After speaking with @lvh about this, I've decided to follow his advice.  Many thanks to @lvh and @glyph for offering their collective expertise in this area.

We represent individual resources via a class.  Two methods are singularly important resources:

* `start` creates the resource, and records sufficient details to allow `stop` to clean up the resource later.  `start` returns a `Deferred` instance, allowing it to be composed with others in a test in a seamless way.

* `stop` destroys the resource using whatever information `start` recorded on its behalf.

Here's an (incomplete) example that I'm working on right as I'm typing this:

```python
class ScalingGroup(object):
    def __init__(self, gc, pool):
        self.group_config = gc
        self.pool = pool

    def stop(self, rcs):
        """Clean up a scaling group."""

        print "STOP(ID(%s))" % self.group_id

    def start(self, rcs, test):
        """Create a scaling group."""

        test.addCleanup(self.stop, rcs)

        def record_results(resp):
            rcs.groups.append(resp)
            self.group_id = resp["group"]["id"]
            return rcs

        return (treq.post(
            "%s/groups" % str(rcs.endpoints["otter"]),
            json.dumps(self.group_config),
            headers={
                'X-Auth-Token': str(rcs.token),
                'Content-Type': 'application/xml',
                'Accept': 'application/xml',
            },
            pool=self.pool
        )
        .addCallback(check_success, [201])
        .addCallback(treq.json_content)
        .addCallback(record_results))
```

You'll notice the `start` method accepts a testcase parameter `test`, on which it invokes the `addCleanup` method.  The clean-up method, `stop` in this case, will be invoked by the test runner at some point in the future.  Otherwise, the `start` method behaves like any other function you'd expect to return a `Deferred`.  Just make sure you include a callback which records your important data!

Using resource classes in this manner is pretty simple as well.  (I think, at least; I'm biased.)  Here's an example from the same spike:

```python
class TestSpike(unittest.TestCase):
    def setUp(self):
        self.pool = HTTPConnectionPool(reactor, False)
        self.identity = lib.IdentityV2(
            auth=auth, username=username, password=password,
            endpoint=endpoint, pool=self.pool
        )

    def tearDown(self):
        def _check_fds(_):
            fds = set(reactor.getReaders() + reactor.getReaders())
            if not [fd for fd in fds if isinstance(fd, Client)]:
                return
            return deferLater(reactor, 0, _check_fds, None)
        return self.pool.closeCachedConnections().addBoth(_check_fds)

    def test_create_scaling_group(self):
        group_configuration = {
            "name": "my-group-configuration",
            "cooldown": 0,
            "minEntities": 0,
        }
        launch_configuration = {
            "type": "launch_server",
            "args": {
                "server": {
                    "flavorRef": flavor_ref,
                    "imageRef": image_ref,
                }
            }
        }
        scaling_group_body = {
            "launchConfiguration": launch_configuration,
            "groupConfiguration": group_configuration,
            "scalingPolicies": [],
        }

        self.scaling_group = ScalingGroup(scaling_group_body, self.pool)

        rcs = lib.TestResources()
        d = (self.identity.authenticate_user(rcs)
             .addCallback(find_end_point)
             .addCallback(print_token_and_ep)
             .addCallback(self.scaling_group.start, self)
             .addCallback(dump_groups)
        )
        return d
```

In `test_create_scaling_group`, we instantiate our `ScalingGroup` resource, telling it which `treq` pool to use, and which request body to use when creating the scaling group.  (This API isn't fixed; it'll probably change in the future once I have a better idea how this function will be used in future tests.)  At this point, a scaling group _has not_ yet been created.

Now, if you look in the creation of the `Deferred` for the test function, you'll see we invoke the start method, passing `self` as our `test` parameter.  Since the resource class automatically registers its own `addCleanup`  callback, we don't have to worry about cleaning up the resource manually in the test case itself.

As I'm writing this update, I've not yet finished the actual deletion logic.  That'll come shortly; but this quick update should be sufficient to show how the flow of control works.

I'm going to close this ticket now that I have an idea how to achieve my goals; however, if anyone has any questions going forward, feel free to update this ticket.
