### ISSUE TITLE
Cover remaining error response codes for CLB update

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#1054]
[Documentation](http://docs.rackspace.com/loadbalancers/api/v1.0/clb-devguide/content/PUT_updateNode_v1.0__account__loadbalancers__loadBalancerId__nodes__nodeId__Nodes-d1e2173.html)

Error response codes: loadbalancerFault (400, 500), serviceUnavailable (503), badRequest (400), unauthorized (401), overLimit (413), itemNotFound (404)

It's kind of ridiculous that 400 is occasionally a load balancer fault and occasionally just a bad request. We don't have to deal with unauthorized; that's the authenticator's problem.

**Comment by manishtomar** [comment]
> It's kind of ridiculous that 400 is occasionally a load balancer fault and occasionally just a bad request.

Its most likely a documentation issue. As far as I've seen, 400 comes only on bad request. But we should confirm from them.

**Comment by manishtomar** [comment]
Asked question to CLB team

**Comment by manishtomar** [comment]
400 code mentioned in docs is actually 422 IMMUTABLE fault which is being handled by `cloud_client.py`. Closing.
