### ISSUE TITLE
RCv3/CLB node removal recovery logic doesn't necessarily terminate

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#1056]
Both of these node removal logics just keep trying. This is fine as long as long as the service doesn't return a response that satisfies the success predicate when no progress was made.

**Comment by cyli** [comment]
Does mean add support for `StepResult.FAILURE`?

**Comment by lvh** [comment]
Possibly; more importantly, it means figuring out when we have failed, which probably means passing an accumulator around so we know how many times we've tried to do this already.

**Comment by cyli** [comment]
Oh so you mean like immediate retries?   I wasn't sure if you meant quit trying to converge that LB after some number of convergence runs too.

**Comment by lvh** [comment]
Right; right now we just return a new Effect, so the retry is immediate and unaffected by the higher level round limit on convergence. (That's a performance optimization, mostly.)

**Comment by cyli** [comment]
Would you mind clarifying the description for this issue then, possibly including subtasks/criteria for finishing?

**Comment by lvh** [comment]
I'm not entirely sure what has to be done to complete it, but I'll add a suggestion.

**Comment by lvh** [comment]
On second thought, I don't think this ticket is actually valid. The only LB that could produce it is CLB, and only if we generate new effects on the fly, which we don't do.
