### ISSUE TITLE
Do whatever it takes to get test_system_server_details_name_and_metadata to work

### ISSUE THREAD

**Issue by radix** [rackerlabs/otter#1059]
(updated based on Ying's comment)

it lives in autoscale_cloudroast/test_repo/autoscale/system/group/test_system_launch_config.py.

It does these things:

- creates a group with 1 min entities
- checks to see if pending + active according to the get group state call is 1
- looks in nova for the servers and makes sure they have the right metadata (no lb metadata checks though), the right image, the right flavor, and the right name

**Comment by cyli** [comment]
I don't think that one actually checks nova - I think it just checks autoscale.  Possibly `test_system_server_details_name_and_metadata`, which:

- creates a group with 1 min entities
- checks to see if pending + active according to the get group state call is 1
- looks in nova for the servers and makes sure they have the right metadata (no lb metadata checks though), the right image, the right flavor, and the right name

**Comment by radix** [comment]
Thanks Ying, there's still a lot I don't know about those tests :) I'll update the description.

**Comment by radix** [comment]
This is fixed now.
