### ISSUE TITLE
Replace errored server with old server

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1097]
From the discussion in #987, looks like requirements are that if a server errors, we want to synthesize what the old launch config should have looked like given the server details, and replace it with a new server created with the old launch config.  Figured the discussion should move to its own issue.

We can possibly do this by:

- Changing gathering of nova data to also grab all data that might be used for a launch config, not just the state data we need
- If a server has errored, create server with a synthesized launch config from the server data, rather than the new launch config
     - This is harder for BFV - we'd probably have to check of the image is null, and if so, check volume attachments, get the volume ID, and check for the volume details and hopefully we will be able to synthesize volume information from that - assuming the user did BFV and create volume all with one command.

It would be simpler just to version all launch configs, and pass converge every single launch config the tenant ever had.

There are some possible optimizations with deleting old launch configs that a user doesn't have anymore.

Question:  what do we replace a server deleted out of band with?

**Comment by glyph** [comment]
[When we last had this discussion](https://github.com/rackerlabs/otter/wiki/Convergence-Specification#desired-behavior), @radix and I wrote up the desired behavior as follows:

> **Servers will always be provisioned using the newest configuration.** "provisioning" includes both creating the server itself and creating the load balancer associations reflected by the scaling group's current state.

> When servers disappear for any reason - hardware failures, Compute API failures, users manually deleting them - Otter should notice and re-provision servers to meet the capacity requirements specified by the scaling group.

If this specification has changed for some reason, that wiki page should be updated to reflect the change.

**Comment by glyph** [comment]
This does seem to be directly contradicted by @wirehead's [https://github.com/rackerlabs/otter/issues/987#issuecomment-74558307 comment] on the other issue though:

> In the case where a server goes into an error state or otherwise disappears/goes bad, we're going to re-provision it with its old launch config, assuming we can.

**Comment by cyli** [comment]
@glyph That comment seems to be exactly what this issue is describing?

**Comment by glyph** [comment]
@cyli - yes, exactly. I was just providing convenient citations of the sources of the two contradictory views of this specification.

**Comment by cyli** [comment]
@glyph Oh ok.  I was confused as to what "this" was referring to (looks like it refers to your previous comment, not the issue in general)

**Comment by glyph** [comment]
@cyli - comment above edited, antecedent made more specific

**Comment by radix** [comment]
yeah this is surprising. why are we doing this?

**Comment by lvh** [comment]
Closing as invalid; we're not doing this for now, and instead just using the current launch config, for most of the arguments already made in this thread.

**Comment by wirehead** [comment]
We'd intended to be conceptually pure ('we don't update you until you tell us to').  After looking at the complexity of doing this, we're changing to the slightly-less-pure but still reasonable version ('if your server dies, you unintentionally are going to do a minor rolling update')
