### ISSUE TITLE
Move `gathering.to_nova_server` to the NovaServer model

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1106]
Could be a classmethod constructor (`from_nova_details` or some such).  From discussion in https://github.com/rackerlabs/otter/pull/1102.

@radix suggests:  I'm also tempted to say that the attributes we expose should also just be properties (or even explicit methods) that look up the data in the stashed json structure.

**Comment by cyli** [comment]
One concern I have with just properties is that it's still nice in the tests to just create model objects without synthesizing Nova server JSON.

One thing we can do is make all the attributes optional, including one for server json, and provide an explicit __init__ function that will:
- populate all the previously required attributes, if they are not provided
- type checks that all the required attributes must be provided, OR the server json must be provided

That seems slightly more complicated though.

**Comment by radix** [comment]
I think we can probably just provide a test-helper function that creates a `NovaServer` (or just dict) with parameters you give it, where everything is optional. There's a `server` function in `otter.test.convergence.test_gathering` which is along these lines already.

conceptually I would like `NovaServer` to just become a well-typed representation of all the data from nova about a server, allowing 1:1 conversion botween the json format and the model object. This would allow implementing `otter.convergence.service.server_to_json` in a more thorough way (and could perhaps just be a method on `NovaServer`)

**Comment by cyli** [comment]
Ok, fair enough

**Comment by manishtomar** [comment]
I feel `NovaServer` could be just data object and there can be top-level functions to construct and deconstruct from JSON.

**Comment by cyli** [comment]
@manishtomar Thanks :)  @radix and I were kind of torn about which way we should go - thank you for the tie-breaking vote!
