### ISSUE TITLE
Logging errors

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#1115]
My current idea is to have class like [`UpstreamError`](https://github.com/rackerlabs/otter/blob/master/otter/util/http.py#L78-L112) that will store `system` as `ServiceType`. This class has `details` property that will return `dict` of internal details and this will be added to the log. 

It will be helpful to decide on this now as it will help in #1130. One option is that instead of returning `Effect (Status, [String])` from `as_effect` it can return `Effect (Status, [Exception])` where exception will be mostly `UpstreamError`. It can be other exceptions also. The advantage is that exception will contain parsed message along with structured info in `.details`. Any other ideas?

**Comment by radix** [comment]
@manishtomar I think we might be overusing `system` -- I'd prefer to keep the service type in a separate dedicated field like `service_type`.

**Comment by radix** [comment]
@manishtomar - I'm a bit confused about what exactly this ticket is about. I see two things:

1. the log system should automatically extract data from `UpstreamError` to include it in log messages in a structured way
2. we should put exceptions in our `reasons` list

The second point is already done-ish (that is, some steps are including exceptions in their reasons list now), but the first isn't. Should this issue be just about the idea of smart logging of exception objects? Or do we have another ticket for that? (The closest I can find is #1107, but that's more general).

**Comment by manishtomar** [comment]
Closing this as we've started putting exceptions in steps result and #1189 is being used to discuss the structure of exceptions to be supported.
