### ISSUE TITLE
Check logstash/kibana for issues.

### ISSUE THREAD

**Issue by sam-falvo** [rackerlabs/otter#1140]
For context, see #1135.

**Comment by cyli** [comment]
Apologies, this is split into a bunch of issues, so I wasn't sure which to reply to.

I notice that a similar test case was already handled by https://github.com/rackerlabs/otter/blob/master/autoscale_cloudroast/test_repo/autoscale/system/integration/test_system_integration_lbaas.py#L131, which updates the group to have 3 load balancers and scales up via executing the policy.

Just in case there was something wrong with webhooks in particular, I tried to replicate the exact series of steps in https://github.com/rackerlabs/otter/compare/replicate-failure-case?expand=1.  This seemed to pass both against mimic and against production systems.

I checked some kibana issues, and there may be an alternative explanation - have sent email, waiting for response.

**Comment by sam-falvo** [comment]
Cause was eventually determined to be operator error on the part of the bug submitter.
