### ISSUE TITLE
DeleteServer should have its own retry loop

### ISSUE THREAD

**Issue by radix** [rackerlabs/otter#1180]
Since 204 from Nova on a delete call can't be trusted, we should implement a loop in the DeleteServer step that checks if the server has actually moved into DELETING, and if not, try again.

It shouldn't be allowed to be infinite, maybe 30-60 seconds, and if we never see DELETING then we should return a RETRY.

**Comment by cyli** [comment]
Two questions:

- the server the state (which is ACTIVE, BUILD, or ERROR), or the task_state?
- do we want a whole loop or just a single call?

**Comment by manishtomar** [comment]
@cyli I think it can just be effect implementation of `worker.verified_delete`.

**Comment by cyli** [comment]
@manishtomar cool, thanks
