### ISSUE TITLE
concretize_service_request should wrap errors in UpstreamError

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1184]
Are we using UpstreamError as a handy parsing thing for logging?

If so, maybe all errors should be UpstreamErrors wrapping APIErrors.  the concretize_service_request knows what service it is, etc.

**Comment by manishtomar** [comment]
Similar question asked in #1115. I would like us to have consensus about what exception to use. Should all be `UpstreamError` or should there be specific types like `CLBPendingUpdate` or `CLBDuplicateNodes`?

**Comment by cyli** [comment]
@manishtomar I do like having specific types because they can be associated with specific event types for logging, otherwise the seem like they may have to append that data to UpstreamError (it just seems strange that something raises UpstreamError, and later on other callbacks examine it and add stuff to it), but maybe that's ok?

I was thinking UpstreamError is a good catchall error though, for errors we don't recognize or handle.

**Comment by cyli** [comment]
Ah apologies, I'm not sure about the specific types (although I think I'm currently slightly biased towards having them), but UpstreamError may be a good catchall exception for types we don't catch specifically?

**Comment by cyli** [comment]
Discussion with @manishtomar:  I guess we can use specific types lie CLBPendingUpdate and CLBDuplicateNodes, and then errors that we don't care about will remain UpstreamError and then be passed in the StepResults?

**Comment by manishtomar** [comment]
Can this be closed since this is getting implemented in #1189 ?

**Comment by cyli** [comment]
Sounds good!
