### ISSUE TITLE
Parse nova/parse CLB errors in steps

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1189]
These should be functions that parse out specific Nova/CLB errors raise them with the relevant info, or reraise the original error.

Then the error handlers can do something with them or not, as desired.

See https://github.com/rackerlabs/otter/pull/1175#issuecomment-78183533

**Comment by radix** [comment]
I'm going to put this in the Servers milestone, though it also applies to the CLB milestone too.

**Comment by manishtomar** [comment]
@radix / @cyli : We need a ticket that decides about the specific error type like `CLBPendingUpdate` / defaulting to `UpstreamError` like error. Can this be that ticket? If so, then I will close #1115 and refer it to this. I originally intended that ticket to be there until we start logging errors or decide how to log them.

**Comment by cyli** [comment]
@manishtomar that sounds good :)

**Comment by cyli** [comment]
Wondering if we should just have 1 error for Nova, like NovaLaunchConfigError or something, that way we don't have to parse the 400 messages.  Otherwise:

-  NovaNetworkInvalidError:  (`Networks (00000000-0000-0000-0000-000000000000) not allowed`, `Networks (00000000-0000-0000-0000-000000000000,11111111-1111-1111-1111-111111111111) required but missing`, and `Exactly 1 isolated network(s) must be attached`)
- NovaQuotaExceededError: (all the quota messages: for RAM, for instances, for onmetal...)
- NovaFlavorError: (invalid flavor, flavor disk too small)
- NovaImageError: (invalid image, image has automatic disk size disabled, image not active)
- NovaSSHKeyError: (invalid key name)
- NovaDiskConfigError: `OS-DCF:diskConfig must be either 'MANUAL' or 'AUTO'.` - we can check for this one in our validation though, and eliminate this as a possible error.
- NovaLaunchConfigError: any 400 from Nova with a message we haven't seen before

**Comment by cyli** [comment]
For CLB:

- CLBDuplicateNodesError - when trying to add a node that already exists to a CLB (not user-visible, we will deal with this one)
- CLBPendingUpdateError - when a CLB is in PENDING UPDATE state and we need to wait a bit (not user-visible - we will deal with this)
- CLBDeletedError - when a CLB is in PENDING DELETE or is deleted - user surfaced error
- CLBNodeRemovedError - when a node no longer exists on a CLB (not user-visible, we can deal with this one I think)
- NoSuchCLBError - when the CLB ID the user gave us is invalid - probably user surfaced?  Maybe we want to validate CLBs when the user submits a launch config though.

**Comment by manishtomar** [comment]
@cyli I don't think our code needs to behave differently based on specific 400 Nova errors. So, I think it should be ok to have single `NovaLaunchConfigError` as long as its `repr` or `message` is user-readable. If needed, we can extend this class in future.

**Comment by cyli** [comment]
@manishtomar Cool - it should be user-readable, since we'll just return whatever Nova gave us.  Although sometimes the messages aren't super specific, like "Invalid key_name provided."

**Comment by cyli** [comment]
These exceptions are basically just going to be bare exceptions though, like:

```
class CLBPendingUpdateError(Exception):
     pass
````

Since there is no real extra information if we are doing the parsing at the service request level

**Comment by manishtomar** [comment]
Since we want to log error with structured information we need to put information in exceptions. For example, `CLBDeletedError` need to have `clb_id` in it. This is especially important since the log with be pushed to cloud feed for customers to consume. To do this, we should have specific APIs in `cloud_client.py` like `clb_add_nodes` that will internally call `service_request`. It will be easy for this API to put structured information in the exceptions raised. The step can then call this API instead of `service_request` directly.

**Comment by cyli** [comment]
And then we can make sure `clb_add_nodes` can never return unexpected errors like `NoSuchCLBNode`, or `clb_change_node` can never return bulk errors.  Cool... :)  Trying this now.

**Comment by cyli** [comment]
Closing this as all that remains is https://github.com/rackerlabs/otter/issues/1267, and moving the RCv3 steps to cloud_client, which is not explicitly part of the issue description or title.
