### ISSUE TITLE
Automated test to monitor convergence behavior when a server goes from active to error state.

### ISSUE THREAD

**Issue by sam-falvo** [rackerlabs/otter#1202]
From Slack chat:

When we have an observer and self-healing, the same behavior in #1201 must apply on a transition from ACTIVE to ERROR.

**Comment by radix** [comment]
This is specifically a series of events like:

- build server successfully through otter
- put that server into ERROR state
- execute a policy (or otherwise get otter to start convergence again)

**Comment by cyli** [comment]
Closing this as this is superceded by by #1320, #1321, and #1322
