### ISSUE TITLE
test convergence recreating servers deleted out of band

### ISSUE THREAD

**Issue by radix** [rackerlabs/otter#1203]
After otter builds a server in a group (and that convergence cycle finished successfully), if the server is deleted and convergence is somehow triggered again, otter should rebuild the server.

**Comment by manishtomar** [comment]
This basically tests #881

**Comment by radix** [comment]
@manishtomar - actually #881 is about load balancers, so that would be a separate test.

**Comment by manishtomar** [comment]
Yeah. You are right. Created #1306 to track CLB issue.
