### ISSUE TITLE
Create scaling group > scalingPolicies > changePercent is wrong about how rounding works

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#1207]
> **changePercent**: Number. Optional.
> The percent change to make in the number of servers in the scaling group. If this number is positive, the number of servers increases by the given percentage. If this parameter is set to a negative number, the number of servers decreases by the given percentage. The absolute change in the number of servers is rounded to the nearest integer. This means that if -X% of the current number of servers translates to -0.5 or -0.25 or -0.75 servers, the actual number of servers that are shut down is 1. If X% of the current number of servers translates to 1.2 or 1.5 or 1.7 servers, the actual number of servers that are launched is 2

1. The documentation claims: "The absolute change in the number of servers is rounded to the nearest integer.". This is not actually how it works. [The code uses `ROUND_UP`](https://github.com/rackerlabs/otter/blob/117132cbd43304ed03bf10381b6f5db118bae3fd/otter/controller.py#L309), which means [round away from zero](https://docs.python.org/2/library/decimal.html#decimal.Context).
2. Even if that is how it worked, that sentence is inconsistent with the examples. The nearest integers to 0.25 and -0.25 is 0, not 1 and -1 respectively as claimed by the example. There is no unique nearest integer to 0.5 and 0.5, either. The good news is that these examples are actually correct; it's just the English description that's bogus.
3. Finally, nitpick: there's a period missing at the end of that sentence.

Resolution: "The absolute change in the number of servers is rounded to the nearest integer." -> "The absolute change in the number of servers is rounded to the nearest integer away from zero." or simply "The absolute change in number of servers is rounded away from zero.". I think the latter is clearer, given that there is an example.

**Comment by manishtomar** [comment]
Based on the [test](https://github.com/rackerlabs/otter/blob/master/otter/test/test_controller.py#L286), 0.25 rounds to 1. Also, that example seems correct w.r.t "round away from zero". If 0.25 rounded to 0, it would be rounding _close_ to zero - not away.

**Comment by lvh** [comment]
Yes, this is why the ticket says:

> The good news is that these examples are actually correct; it's just the English description that's bogus.

**Comment by lvh** [comment]
Closing this manually since DevDoc doesn't add `Closes:` lines to commits.
