### ISSUE TITLE
throttle server creation requests in worker code

### ISSUE THREAD

**Issue by radix** [rackerlabs/otter#1221]
Nova doesn't want us to hit them with multiple concurrent Create Server requests, so we need to make sure we're putting gaps (of about 1 second) in between each POST to /servers.

**Comment by lvh** [comment]
Some boring issue tracker management points:

- I don't know if this changed during the creation of this ticket, but this was given to various upstream Compute folks as the place to track it *right now*, which is about worker
- There already was a ticket for doing this in convergence: https://github.com/rackerlabs/otter/issues/866, where the theory was posited that the stuff we will be doing for convergence is sufficient.

Would it be OK to make this ticket be about worker instead?

**Comment by radix** [comment]
It didn't change, this ticket was always intended to be about converger, not the worker. I was thinking something more specific than #866 with this ticket, specifically so it doesn't require multiple convergence cycles.

Given that nova folks are tracking *this* ticket now, though, it's fine to repurpose it.

**Comment by lvh** [comment]
OK, cool, thanks. Would you like me to create another ticket for convergence? (I don't think anything has changed since I closed #866; I still don't know if it will actually be necessary to implement more throttling once we have convergence.)

**Comment by lvh** [comment]
Closed by #1224. Not yet deployed.

**Comment by radix** [comment]
I've created #1225 to represent the original intent of this ticket.

**Comment by lvh** [comment]
Awesome, thanks!
