### ISSUE TITLE
some webhook keys disappearing

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#1223]
I noticed few instances of webhook keys being there in `policy_webhooks` but not in `webhook_keys`. From the logs, the webhook key was created *and* used successfully on Feb 23rd but for some reason not available today. I have currently added these using `python load_cql.py --webhook-migrate`. We might need to check again sometime in future by `python load_cql.py --webhook-index-only` and see if it still happens.

**Comment by manishtomar** [comment]
Correct fix in #1345

**Comment by cyli** [comment]
This seems to have been fixed.  Can we close?

**Comment by manishtomar** [comment]
Yes. I guess I forgot to close with last comment. Closing.
