### ISSUE TITLE
Structured error from load balancer steps should specify load balancer type

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#1259]
Additionally, it should specify node id and load balancer id. This is for both RCv3 and CLB.

**Comment by cyli** [comment]
Only in the case of non-errored structured data, right?  Otherwise, the error type specifies what kind of load balancer it is?

**Comment by lvh** [comment]
Yep :)

**Comment by manishtomar** [comment]
All the CLB steps now use cloud client functions which raise structured exceptions. Closing.
