### ISSUE TITLE
Return 404 on DELETED groups

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#1265]
As part of implementing #1179, otter is changing group status instead of actually deleting the group. Hence, to keep API compatible it should return 404 on all the REST calls on the DELETED group. This was suggested in https://github.com/rackerlabs/otter/pull/1261#issuecomment-87070437. 

This can be done by returning `NoSuchScalingGroupError` on all model APIs except `get_status` API.

**Comment by radix** [comment]
fixed by #1268.
