### ISSUE TITLE
Delete server after CLB Not Found error while adding the node?

### ISSUE THREAD

**Issue by radix** [rackerlabs/otter#1305]
The behavior of the legacy worker is to delete the server and all other node associations it has when there's a 404 from adding it to a CLB.

The behavior of Convergence is to fail the convergence and (soon) put the group into ERROR state, while leaving the server there.

This behavior is tested with `test_group_with_invalid_load_balancer_among_multiple_load_balancers` in in `test_system_integration_lbaas.py`.

**Comment by radix** [comment]
I'm actually having second thoughts and thinking we should just leave everything as-is. As long as we put the group into ERROR and emit an event on cloud feeds the user should be able to rectify it themselves.

**Comment by manishtomar** [comment]
I think putting it in ERROR with info in cloud feeds is a better approach. We should probably document this as a behavioral change in convergence.

**Comment by manishtomar** [comment]
Added doc change https://github.com/rackerlabs/otter/wiki/User-facing-convergence-changes#behavioral-changes. This has been in code for quite sometime. 

Closing

**Comment by radix** [comment]
Thanks :)
