### ISSUE TITLE
CATC1: Basic scale up

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1310]
Convergence Automated Test Case 1

Scale Up: Given the number of permutations of this test, this will use generative testing to exercise various scaling factors, min/max constraints, policy types, and load balancers
- Create a scaling group with various launch configuration data
- Scale up by X servers
- Validate end group state

This test case represents a template for a set of generative tests. Select one case to automate as a representative sample.

This test case is not convergence specific, and the scenario is already tested in the Cafe tests.

**Comment by sam-falvo** [comment]
What needs parameterization specifically?  I have this case covered in the existing body of Trial tests, though it is a bit static.

**Comment by kivattik** [comment]
Regarding existing tests: The 'qe: cafe overlap' tag was included to indicate that static tests already exist, although I wasn't aware they were in Trial. I'm open to alternate tag names that are more informative.

I think the action on this issue for now might just be to link to the existing test cases in this issue and in the test case document. 

RE parameterization: See comments on #1311
