### ISSUE TITLE
CATC3: Basic multiple scaling policies

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1312]
Multiple Scaling Policies: Given the number of permutations of this test, this will use generative testing to exercise various scaling factors, min/max constraints, and cloud load balancers
	- Create a scaling group with various launch configuration data
	- Create X scaling policies, some increasing and some decreasing (different types?)
	- Apply the policies in sequence 

This case is not convergence specific and exists in the cafe tests

**Comment by sam-falvo** [comment]
What is the interface between the generative tester and our Trial tests?  I was under the impression that the Clojure code was self-sufficient, and did not shell out to invoke other test frameworks.  So, in other words, how do we parameterize this in a meaningful way?

**Comment by kivattik** [comment]
Short answer, I think we need a discussion to address all those points since I do not have good answers.  The classification of this issue should probably chance since I was viewing it more as a place-holder.

The 'qe: cafe overlap' tag was included to indicate that this issue is not a priority since the cases are covered elsewhere.
