### ISSUE TITLE
CATC5: Scale up after out of band delete

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1314]
OOBD: Scale up after out of band delete, non constrained
	- Create a group with min N servers
	- Scale group to (N+ x) servers
	- Delete one of the servers out of band
	- Scale up by (y) servers
        - Expect N + x + y servers eventually (i.e. the deleted server is replaced and the y scale is executed on top of that.)

**Comment by sam-falvo** [comment]
Can you edit the description above to include desired outcome?  Thanks.

**Comment by kivattik** [comment]
I've update the description to include an expected end state of N+x+y.
