### ISSUE TITLE
CATC6: Scale down after out of band delete

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1315]
OOBD: Scale down after out of band delete, non constrained
	- Create a group with min N servers
	- Scale group to (N+ x) servers
	- Delete z of the servers out of band
	- Scale down by (y) servers
	- Validate end state of (N + x  - y) servers
		- Consider the case where z == y

**Comment by sam-falvo** [comment]
This seems to be a special case of #1314, where z=1 and y<0 (where scaling down by -1 server is == to scaling up by 1).  I'd argue these two cases are, therefore, the same thing.  Thoughts?

**Comment by kivattik** [comment]
As a generative template, I would agree they are the same thing. Since these are being specifically implemented as representative cases for automation however, I think that there is value in including both a scale up and scale down operation. They probably execute the same code path, but for black box testing we can't assume that is the case.
