### ISSUE TITLE
CATC8: Update launch config after OOB delete

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1317]
aka - trigger convergence after OOB delete
OOBD: Update the launch config after an OOB delete
	- Create a group and scale to N, where N > min
	- Delete a server out of band
	- Update the ~~launch~~ group config (ex. change the group MAX)
	- Validate that updating the config triggered convergence back to N servers
		- White-box test?

**Comment by sam-falvo** [comment]
Changing the group to MAX (I am guessing you mean the group's minimum to MAX here?) is a different thing than touching the launch configuration, no?  Wouldn't it be better to try and alter the launch config itself (e.g., the flavor used, or the image)?

**Comment by kivattik** [comment]
That was not a well thought out example and can be ignored. (Although for the record I was thinking just increasing the MAX even when nowhere near hitting it to make a trivial change.) The intent is to do something to trigger convergence without changing the expected end state, and the Otter specification should be checked to determine exactly what triggers convergence.
