### ISSUE TITLE
CATC9: Server Transitioned to Error (STE): STE from Building

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1318]
Server Transitioned to Error (STE): STE from Building
	- Validate that the expected group state is reached when servers error on build

**Comment by cyli** [comment]
If this is only going to transition 1 server of N into building (without any changes to launch config/convergence) then this is probably blocked on https://github.com/rackerlabs/mimic/issues/204

**Comment by cyli** [comment]
Actually https://github.com/rackerlabs/mimic/issues/233 has been resolved, which we can probably use for this now.
