### ISSUE TITLE
CATC15: Scale to CLB max after OOBD

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1323]
OOB w/CLB: (WHITEBOX) Scale to CLB max after OOBD (NOTE: There are possibly 2 test cases here, one with group max > CLB max, the other with group max == CLB max)
	- Create a scaling group
	- Scale to 24 (CLB max -1) servers
	- Delete ‘2’ servers OOB
	- Attempt to scale up by 1 server (to CLB max)
	- Validate that group attempts to return to 25 servers and does not overshoot
		-Confirm that the deleted servers were removed from the CLB

**Comment by sam-falvo** [comment]
I'm going to change the parameters of this test somewhat.

If we delete 2 servers OOB, then scale up by 1, even with convergence turned off, we end up with 25 servers in the active state when we poll Otter.  Thus, we need to scale down by one first, then scale up again.  This gives us a chance to wait for Otter to catch up with Nova and actually verify it.
