### ISSUE TITLE
CATC17: Scale over group max after metadata removal, Where Group MAX < CLB max 

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1325]
Metadata w/CLB: (WHITEBOX) Scale over group max after metadata removal, Where Group MAX < CLB max (NOTE: Autoscale does not take responsibility for incorrect behavior after metadata tampering)
	- Create a scaling group
	- Scale to MAX servers
	- Remove Autoscale metadata from ‘z’ servers
	- Attempt to scale up (i.e. beyond max)
	- Validate that group returns to max associated servers and does not overshoot
	- Confirm that other scaling groups on tenant are not impacted

**Comment by sam-falvo** [comment]
Just to clarify, shouldn't the step list read as follows?

```
- Create two scaling groups, one with 0 servers, one with 0<N<MAX servers.
- Scale first group to MAX servers
- Remove Autoscale metadata from ‘z’ servers
- Attempt to scale up first group (i.e. beyond max)
- Validate that group returns to max associated servers and does not overshoot
- Validate active servers in that group no longer list servers with missing metadata.
- Confirm that other scaling group on tenant are not impacted
```
