### ISSUE TITLE
CATC18: Scale over group max after metadata removal, Where Group MAX == CLB max (25)

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1326]
Metadata w/CLB: (WHITEBOX) Scale over group max after metadata removal, Where Group MAX == CLB max (25)
	- Create a scaling group
	- Scale to MAX servers
	- Remove Autoscale metadata from ‘z’ servers
	- Attempt to scale up (i.e. beyond max)
	- Validate that group attempts to return to max associated servers and does not overshoot
		- It is expected that this group would enter an error state due to being unable to add servers to the load balancer

**Comment by sam-falvo** [comment]
Per discussion with Ying, closing issue as this condition isn't valid, and adds no value to existing test CATC16.
