### ISSUE TITLE
CATC20: Scale group with CLB deleted partway

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1328]
Scale group with CLB deleted partway
	- Create a group and scale by x
	- Delete the CLB or otherwise cause it to return 404
	- Attempt to scale up
	- validate that the group enters a TBD error state

In order to make this convergence specific:
- remove a server from each LB out of band and expect them to be readded

Prereq: There MUST be a defined backoff/Invalid group behavior defined.
Prereq: We MUST be able to use Mimic to delete a CLB

**Comment by cyli** [comment]
Oops!

**Comment by cyli** [comment]
Should "remove a server from each LB out of band and expect them to be readded" be part of #1329 (CATC21) instead?

**Comment by manishtomar** [comment]
> Should "remove a server from each LB out of band and expect them to be readded" be part of #1329 (CATC21) instead?

+1. This test should only be about group going into ERROR on deleted CLB.
