### ISSUE TITLE
CATC22: Multiple CLB, one goes into Error then fixes itself

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1330]
Suspended
========

Multiple cloud load balancers, one goes into Err/Invalid before scale up
	- Create a group with 2 CLBs & non-min servers
	- Use mimic to cause one of the load balancers to go into ERROR
	- Attempt to scale up
        - Confirm that group enters error state

Prereq: MUST be able to use Mimic to place a CLB into a Error/Invalid state

This test will simulate a LB error due to running out of virtual IPs. This should transition to error state since the fix is to contact support to allocate more. The status is ERROR, and an add request returns a 500 response code with the message "Out of virtual IPs. Please contact support so they can allocate more virtual IPs." (http://docs.rackspace.com/loadbalancers/api/v1.0/clb-devguide/content/outOfVirtualIps-d1e1261.html)

**Comment by sam-falvo** [comment]
Why would no progress be made?  Wouldn't we just provision servers to use the CLB-B instead?

**Comment by kivattik** [comment]
Unless I misunderstand the expected behavior (which is certainly possible), the server creation should rewind if it cannot be added to both CLBs since both were specified. This test could also be valid for a single load balancer going into error and fixing itself, but I wanted to ensure that the multiple load balancer path was executed.

**Comment by manishtomar** [comment]
There is discussion in #1305 about what should converger do if CLB given is not found and we are leaning towards putting the group in ERROR state and leaving everything as-is. This would be the same if CLB ERRORed. So, assuming we finalize this behavior, the test should check if group is put in ERROR if CLB is in ERROR. IMHO, we can start with simple 1 CLB test which calls `POST ../groupId/converge` after the CLB becomes ACTIVE and ensures that group converges. The multiple load balancers can be separate test.

**Comment by kivattik** [comment]
Group Error State: When a get state is performed, the state will be Error

**Comment by cyli** [comment]
@kivattik Apologies, what are the two test cases?  with 1 CLB and with 2 CLBs?

**Comment by kivattik** [comment]
This needs clarification from the CLB team on the ERROR responses before we can decide how to handle them.
