### ISSUE TITLE
CATC24: Simulate Nova 40x's

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1332]
Based on comments that the group should fail at any 40x

(This was split into two sections: Recoverable 401/500, and error on 400)

Simulate Nova 40xs, and verify that the group enters ERROR state
	- For each of the following:
		- 403:  Not allowed to boot from image
		- 403: Access was denied
		- 400: Image not active
		- 400: Bad Networks Format

Prereq: MUST be able to use Mimic to simulate error cases

**Comment by sam-falvo** [comment]
This isn't specified appropriately.  What's the desired outcome for each of the four error conditions listed above?

**Comment by kivattik** [comment]
Good point. I see three different possible cases here. (Assuming that the reaction for each 40x error is the same)

1.) Periodic 40x: Similar to periodic auth failure, just keep trying and eventually it is expected to reach the desired state

2.) Non-Periodic 40x with config fix: 
Need to get specification of the following: if I attempt to execute a policy with an incorrect launch configuration (ex. image not active) and then fix the launch configuration, is the expected behavior to converge using the new launch configuration or should the group enter an error state since the request as made is impossible to fulfill?

3.) Constant 40x: ( if config change does not apply): 
The group should enter an error state or exhibit back-off behavior that needs to be clearly specified.

**Comment by manishtomar** [comment]
I think converger will fail on any 400 and put the group in ERROR. We've still not decided how and when to bring the group back to ACTIVE once it has gone to ERROR. Most likely, any config change or special `POST ../groupId/converge` call will enabled the group and trigger convergence with _latest_ launch config but need to confirm this as a requirement.

**Comment by cyli** [comment]
Dependent upon https://github.com/rackerlabs/mimic/pull/263

**Comment by kivattik** [comment]
The only one of the three cases that needs tested in this issue is 1. Recoverable error codes that occur periodically are retried until the group eventually reaches the desired state. 

Error codes that cause a direct transition to error state are covered elsewhere.
