### ISSUE TITLE
CATC27: Force overshoot condition 

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1335]
Force overshoot condition by altering config (NOTE: There are safeguards to prevent lowering MAX below actual. This might require instrumented injection or the case be deemed unneeded)
	- Create a scaling group
	- Scale to N servers
	- Update launch config to max less than N
	- Expect excess servers to be deleted

Prereq - Determine if this case is possible without manual manipulation of the state data
Prereq if Needed: Must be able to manually alter autoscale state information 

Note: This test might be deemed invalid due to impossibility or difficulty injecting on the needed whitebox level.

**Comment by cyli** [comment]
This is already covered by the cloudcafe test here:  https://github.com/rackerlabs/otter/blob/master/autoscale_cloudroast/test_repo/autoscale/system/group/test_system_group.py#L44

And convergence is currently passing on it.

**Comment by kivattik** [comment]
Closing: This test duplicates cafe tests.
