### ISSUE TITLE
CATC28: Force undershoot condition

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1336]
Force undershoot condition by altering config
	- Create a scaling group with X min servers
	- Scale up by Y servers
	- Update launch config to min = X + Y -1
	- Validate expected group state

Prereq - Determine if this case is possible without manual manipulation of the state data
Prereq if Needed: Must be able to manually alter autoscale state information

Note: This test might be deemed invalid due to impossibility or difficulty injecting on the needed whitebox level.

**Comment by cyli** [comment]
This may already be covered by https://github.com/rackerlabs/otter/blob/master/autoscale_cloudroast/test_repo/autoscale/system/group/test_system_group.py#L31

**Comment by kivattik** [comment]
Closing: This test duplicates cafe tests.
