### ISSUE TITLE
CATC29:  Simulate accidental overshoot due to Nova 500 without an actual failure

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1337]
Simulate accidental overshoot due to Nova 500 without an actual failure
	- Create a scaling group
	- Scale up by X
	- Use mimic to cause Nova to return a 500 but build the server anyway
	- Confirm that any excess builds are stopped and the correct number of servers is produced

Prereq: Mimic MUST be capable of returning a Nova 500 and creating the server anyway.

**Comment by cyli** [comment]
Would it be sufficient for all X to fail with a 500?   Or does it have to be only 1?

Regardless, I'll add a behavior for making nova 500 but create a server anyway.

**Comment by cyli** [comment]
https://github.com/rackerlabs/mimic/pull/249

**Comment by lekhajee** [comment]
@kivattik : Could you please add the Mimic related requests under issues on the mimic repo.
