### ISSUE TITLE
CATC30: Scheduled Policy Interactions (Possibly redundant with Cafe tests)

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1338]
Scheduled Policy Interactions (Possibly redundant with Cafe tests)
	- Test the following scenarios
		- Scheduled scale up/down policy executed during scale up/down by percent
		- Scheduled scale down policy executed during scale up/down by increment
		- Scheduled scale up/down policy executed during scale to exactly

**Comment by sam-falvo** [comment]
Can you better define what "during" means?  Also, it looks like you have an unfinished 3rd sentence.

**Comment by kivattik** [comment]
Closing: This test duplicates cafe tests.
