### ISSUE TITLE
When executing a scaling policy in convergence, refuse to execute if we are already at MAX

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1344]
In the worker, if delta is 0, we raise `CannotExecutePolicyError` (because the converge() function returns None).  In the convergence case, we never return None from the `converge() function`, so `CannotExecutePolicyError` is never raised.

As @kivattik suggests, we should probably run convergence anyway, but still raise the exception.

**Comment by cyli** [comment]
The first part is being handled by #1309

**Comment by manishtomar** [comment]
Closing as #1309 has been merged.
