### ISSUE TITLE
Throttle deletion

### ISSUE THREAD

**Issue by wirehead** [rackerlabs/otter#1411]
Throttle deletions to approx 300 delete requests per minute in the existing non-convergence codebase.

**Comment by joeracker** [comment]
@manishtomar did this get pushed to prod?

**Comment by cyli** [comment]
@joeracker Not yet, that will be today.

**Comment by joeracker** [comment]
@cyli Thanks.  Any idea what time?

**Comment by manishtomar** [comment]
@joeracker Done today morning.

**Comment by joeracker** [comment]
manishtomar: thanks for the response.  Do you know what time it was deployed?  We saw another spike today at around 12 noon CDT that exceeded our target 300RPM.

**Comment by cyli** [comment]
@joeracker: It was a staggered deploy, the first of which that started around 11:15 AM PST (so the spike at 12 noon was probably before the deploy).
