### ISSUE TITLE
Contribute StubTreq and StubResponse to upstream treq as a testing utility

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1423]
As suggested by @manishtomar:
1. so we don't have to maintain it in our test utils and 
2. it seems like it'd be useful for other projects too.

**Comment by cyli** [comment]
https://github.com/twisted/treq/pull/96

**Comment by manishtomar** [comment]
Can this be closed?

**Comment by cyli** [comment]
Yes, sorry!  :D  there are still other PRs on treq, but it's already partially done, so we can close this :)
