### ISSUE TITLE
Walk backwards to find draining time for CLB nodes

### ISSUE THREAD

**Issue by radix** [rackerlabs/otter#1443]
From gathering.py extract_CLB_drained_at:

TODO: This function temporarily only looks at last entry assuming that it was draining operation. May need to look at all entries in reverse order and check for draining operation. This could include paging to further entries

We're only looking at the last event in a CLB feed. We need to walk the events backwards until we find the relevant one, since other events may happen on CLB nodes.

**Comment by manishtomar** [comment]
Closing as it has been fixed in #1443.
