### ISSUE TITLE
CreateServer should fail on 403-over quota errors

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1470]
When the user gets their quota issues fixed, we can converge again.

**Comment by manishtomar** [comment]
The group should be put in ERROR right?

**Comment by manishtomar** [comment]
Also, sorry how is this a bug?

**Comment by kivattik** [comment]
Yes, on getting a quota error I would expect the group should be put into ERROR. I'm not sure (need to ask cyli), but I was guessing it was labeled a bug since there was an expectation this behavior was already present.

**Comment by manishtomar** [comment]
Yeah. From looking at the code, it looks like it should've been handled. Hence the bug label. Thanks :)

**Comment by cyli** [comment]
Sorry, I was wrong, this was not the bug.  Over quota issues are handled and result in the group going into ERROR.  Apologies, the bug is in marking the group as ACTIVE after it's been in error.   Closing this in favor of #1505.
