### ISSUE TITLE
Group does not enter ERROR when CLB is PENDING_DELETE during a scale up

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1475]
Running a mimic test to simulate getting a 422, PENDING_DELETE does not cause the group to enter error, it continues to retry. (See Convergence Automated Test Case 23)

**Comment by cyli** [comment]
It looks like this is a mimic bug.  The message that comes back from mimic is:

`Load Balancer '45215' has a status of PENDING_DELETE and is considered immutable.`

We are expecting PENDING_DELETE to be in quotes.  I'll file a bug against mimic, and file a new bug against otter that maybe we should be a little fuzzier in our regex's.

**Comment by cyli** [comment]
https://github.com/rackerlabs/mimic/pull/322 was merged, and https://github.com/rackerlabs/otter/pull/1498 was created to unskip the test.
