### ISSUE TITLE
RCv3 gathering on `NoSuchEndpoint`

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#1477]
`otter.convergence.gathering.get_rcv3_contents` should fail immediately if it gets `NoSuchEndpoint` error instead of retrying till the end. This is required since RCv3 is opt-in service for tenants and long retries in gathering causes certain tests to fail.

**Comment by cyli** [comment]
Fail (e.g. no retry), but we probably want to catch that error and return an empty list instead, because it's actually a gathering success if there's no such endpoint.

**Comment by manishtomar** [comment]
Yes thank you. Thats what I intended. We should return empty list for the cycle to continue :)
