### ISSUE TITLE
LBSH-002 Servers managed by autoscale SHALL be...1 group, LB1 in config, LB2 not in any autoscale configs

### ISSUE THREAD

**Issue by sam-falvo** [rackerlabs/otter#1482]
Servers managed by autoscale SHALL be only on the nodes on the load-balancers in their launch config after convergence is triggered.

1 group, LB1 in config, LB2 not in any autoscale configs:

Server node moved from LB1 to LB2
Assert: Server put back on LB1
Assert: Server removed from LB2

**Comment by cyli** [comment]
Fixed in  #1560
