### ISSUE TITLE
LBSH-004: Load balancers used in ... 1 group, 1 LB in config, N > 2 non-autoscale servers on LB

### ISSUE THREAD

**Issue by sam-falvo** [rackerlabs/otter#1484]
Load balancers used in autoscale configureations MAY have non-autoscale servers on them and Convergence SHALL only clean up servers managed by autoscale.

(This test is largely covered by the others, but it is straightforward and can also be applied to RCV3 so I would advocate including it anyway.)

1 group, 1 LB in config, N > 2 non-autoscale servers on LB: 

Servers should be directly created with Nova and added in a way that allows reuse for CLBs and RCV3

Remove Autoscale server from LB
Remove 1 non-otter server from LB

Assert: AS server is put back
Assert: non-otter server is not put back
Assert: Untouched non-autoscale servers are untouched

**Comment by cyli** [comment]
Oops, this was done in https://github.com/rackerlabs/otter/pull/1564.
