### ISSUE TITLE
Tests that convergence will make sure autoscaled servers ... 1 Scaling group on 1 CLB with other non-autoscale nodes

### ISSUE THREAD

**Issue by sam-falvo** [rackerlabs/otter#1491]
Tests that convergence will make sure autoscaled servers put CLB nodes back in the state they should be in:

1 Scaling group on 1 CLB with other non-autoscale nodes
Change 1 server’s CLB node status
from ENABLED to DRAINING
from weight 1 to 2
from PRIMARY to SECONDARY
Trigger convergence
Assert: all autoscaled servers should be in ENABLED mode, weight 1, PRIMARY

**Comment by cyli** [comment]
This doesn't work for draining because Mimic does not yet support the atom change feed for CLBs yet, so gathering fails repeatedly.
