### ISSUE TITLE
Slightly fuzzier regexp matching when parsing error messages from CLB and Nova

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1497]
https://github.com/rackerlabs/otter/issues/1475 was an issue where a slight discrepancy in mimic broke the test.

While this is not necessarily a bad thing, we don't have a full enumeration of all possible CLB errors (in Nova at least maybe we can look through the source), so maybe it'd make sense to make the regex matches slightly fuzzier?

**Comment by cyli** [comment]
For instance, we have regexes like this currently:

```
_CLB_IMMUTABLE_PATTERN = re.compile(
    "^Load Balancer '\d+' has a status of '[^']+' and is considered "
    "immutable\.$")
_CLB_NOT_ACTIVE_PATTERN = re.compile("^LoadBalancer is not ACTIVE$")
_CLB_DELETED_PATTERN = re.compile(
    "^(Load Balancer '\d+' has a status of 'PENDING_DELETE' and is|"
    "The load balancer is deleted and) considered immutable\.$")
_CLB_MARKED_DELETED_PATTERN = re.compile(
    "^The loadbalancer is marked as deleted\.$")
_CLB_NO_SUCH_NODE_PATTERN = re.compile(
    "^Node with id #\d+ not found for loadbalancer #\d+$")
_CLB_NO_SUCH_LB_PATTERN = re.compile(
    "^Load balancer not found\.$")
_CLB_DUPLICATE_NODES_PATTERN = re.compile(
    "^Duplicate nodes detected. One or more nodes already configured "
    "on load balancer\.$")
_CLB_NODE_LIMIT_PATTERN = re.compile(
    "^Nodes must not exceed \d+ per load balancer\.$")
_CLB_NODE_REMOVED_PATTERN = re.compile(
    "^Node ids ((?:\d+,)*(?:\d+)) are not a part of your loadbalancer\s*$")
_CLB_OVER_LIMIT_PATTERN = re.compile("^OverLimit Retry\.{3}$")
```

Maybe we can do case-insensitive matches, remove the `$` and remove the requirement for a period to end the message?

**Comment by glyph** [comment]
Given that CLBs is the only CLB-like API out there, I think we might want to fix this by modifying Mimic to match more exactly.

But what do you mean by "fuzzier"?  Just "bigger globs on wildcard groups" or "case insensitive flags"?

**Comment by manishtomar** [comment]
Ideally, if CLB gave us the exact error format, it would make sense to match exact strings. Without that, I think its ok to not have very strict checking.

**Comment by radix** [comment]
I have no problem with removing ^ and $ and periods.

Oh hey and I just noticed one of our periods is unescaped, in the middle of `_CLB_DUPLICATE_NODES_PATTERN`

**Comment by radix** [comment]
And also I would be fine with using `re.I`.
