### ISSUE TITLE
Post convergence groups should error on any 400 from Nova

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1510]
As discussed in the comments on #1332, when a group receives a 400: BadRequest response from Nova, the group should transition to ERROR state.

**Comment by cyli** [comment]
Oops!  I'm sorry, I think it does but we don't have a test for it.

**Comment by cyli** [comment]
Nm, I just saw #1511 :D

**Comment by cyli** [comment]
We currently error on exact parsable 400s, but this issue and title still applies and we should error on ANY 400, not just the ones with JSON 'badRequest'
