### ISSUE TITLE
Convergence test delete server should wait

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#1528]
Convergence test that delete server OOB do not work on prod Nova since Nova takes time to delete servers. When deleting server, it should wait for the server to be actually deleted by ensuring its GET call returns a 404.

**Comment by manishtomar** [comment]
I've implemented this and pushed it but have not written tests for it. See https://github.com/rackerlabs/otter/compare/test-delete-server-waits

**Comment by cyli** [comment]
Was this closed by #1537?

**Comment by manishtomar** [comment]
Yes. Thank you for noticing. Closing this.
