### ISSUE TITLE
otter should stop after scheduler service stops

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#1539]
This is how it was earlier but has changed since partitioner has been split out for converger. Currently, return value of [`got_buckets`](https://github.com/rackerlabs/otter/blob/master/otter/util/zkpartitioner.py#L117) is ignored due to which scheduler can lose events that it was triggering at that time. The right solution for this #1400 but until then I think its best that otter continues to run until scheduler interval completes.

**Comment by manishtomar** [comment]
@radix Have you seen this? Any thoughts?

**Comment by radix** [comment]
I didn't intend to change the semantics of service shutdown in the scheduler, so if they did change then it's a bug, sorry :(
