### ISSUE TITLE
Using the server cache for the active servers returned by state

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1558]
The Autoscale active server cache (AASC) != the Nova server cache (NSC), because the autoscale active servers are on the CLBs they should be on, whereas the server cache would only give us servers that Nova considers active.

We'd like to be able to synthesize the AASC from the NSC, partially because it's the same information in two places, partially to reduce lock contention.

But the NSC doesn't have any information about CLB, so this issue is to serve as a sort of place to discuss ways we can get around this, whether we should do this, etc.

Possibilities:

1.  Just re-gather from Nova and CLB every time the user queries state.  This seems expensive for Nova and CLB though - people poll Autoscale, and we in turn would be polling Nova + CLB every time we were polled, as well as every time we converge.  This might overload Nova, not to mention that it may make our GET request responses very slow.

2.  Gather active servers from nova from the NSC, and just query CLB every time the state is is requested - we don't actually care about the entire state of the CLB world, so we could only get the load balancers that we cared about, making it less expensive than a full gather.  Not sure how CLB will feel about this.

3.  Instead of writing to the state when we want to update the AASC, we write a boolean to the NSC stating whether autoscale considers the server ID fully active.  That way, we can query the NSC to synthesize the AASC by filtering out all servers that don't have the boolean set to True.  We don't need a lock, because one api node can write to the NSC at a time due to partitioning, and if that fails, eh... it's a cache.  ~~The problem is we have to figure out a way to ship the last updated timestamp around.~~ 

    If we write the cache at every gathering, the we have the last updated time in `execute_convergence`, which passes that time to the gathering and can also pass it to `_update_active`.

**Comment by radix** [comment]
I'm happy with #3, and I think we should move the cache-updating out of gathering.py and into execute_convergence, unifying all of our cache-updating to one place.

**Comment by cyli** [comment]
Can this be closed now?

**Comment by manishtomar** [comment]
Oh yes. Closing as fixed in #1567.
