### ISSUE TITLE
Handle CLB in BUILD state by RETRY-ing

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1559]
Some of our cafe tests is failing in production because the load balancers are building and nodes can't be added to them.  We should retry on BUILD.

status code: 422
body:
`{"message":"Load Balancer '42473' has a status of 'BUILD' and is considered immutable.","code":422}`

**Comment by manishtomar** [comment]
As in convergence should be retried? or tests should retry?

**Comment by cyli** [comment]
Er sorry, convergence should retry.  The step should return RETRY.
