### ISSUE TITLE
Add alter table migration for server cache table

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1574]
To add the one additional column.

**Comment by manishtomar** [comment]
I would've done if we run migrations. I wonder what is the right time to put migrations in that directory.

**Comment by manishtomar** [comment]
Unfortunately, we've to _remember_ alter table before next deploy. So, I guess having it in migrations helps.

**Comment by cyli** [comment]
Yeah.  :(  Mostly I wanted to put this hear so that we remember to do so before deploying.

**Comment by manishtomar** [comment]
Closing as this has been deployed few weeks ago.
