### ISSUE TITLE
"error_reasons" field in group state

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#1578]
This new field will be returned inside "state" whereever group state is returned in REST API (`/groupId/state`, `/groups/groupId` and `groups/`). It will contain `;`-separated list of reasons why the group is in ERROR. When the group is ACTIVE, this field will not be there. Hence state will look like 
```
      "state":{
         "active":[
         ],
         "status": "ERROR",
         "error_reasons": "Cloud load balancer 2134 has been deleted; Invalid imageRef 605e13f6-1452-4588-b5da-ac6bb468c5bf".
         "activeCapacity":0,
         "desiredCapacity":0,
         "paused":false,
         "pendingCapacity":0,
         "name":"smallest possible launch config group"
```
The reasons will contain same content that is injected to CF [at the end of convergence](https://github.com/rackerlabs/otter/blob/7794ab65fa7b0b990a3318263158bcf51159735d/otter/convergence/service.py#L233-L235).

Can be split up into:
- [x] Convergence putting reasons in DB
- [x] REST returning reasons in state calls

**Comment by cyli** [comment]
Just to keep track of what we're doing, I think from discussion, we are probably just going to name the field `"errors": []`.

It will be a list of dictionaries that look like:  `[{"message": ....}, {"message": ....}]`

That way, if we wanted to insert an error type or error UUID or error link to documentation that explains how to fix it or something, we won't have to deprecate the API or add a new field.

Does that sound accurate?

**Comment by manishtomar** [comment]
Yes @cyli . Thank you so much for updating it here.

**Comment by cyli** [comment]
Closing since this #1608 got merged and integration tests (against mimic) pass :)
