### ISSUE TITLE
Gathering CLB blows up if a load balancer has been "marked deleted"

### ISSUE THREAD

**Issue by radix** [rackerlabs/otter#1599]
Gathering doesn't handle 410 "The loadbalancer is marked as deleted", and the exception bubbles all the way up to convergence and causes it to retry. This basically means that convergence will be stuck until load balancers completely disappear from CLB, which doesn't seem to be that long in practice, but it's still something we should handle.

**Comment by radix** [comment]
This may be a chance to move some of the gathering functionality to cloud_client.py to take advantage of its exception processing.

**Comment by manishtomar** [comment]
I think this was completed 1-2 weeks ago right? If so, this can be closed.

**Comment by cyli** [comment]
I think so, yes.
