### ISSUE TITLE
Implement pause

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1604]
The endpoint is already implemented (https://github.com/rackerlabs/otter/blob/master/otter/rest/groups.py#L665), but the functionality is not (https://github.com/rackerlabs/otter/blob/master/otter/controller.py#L84).

As per discussions, "paused" state and "status" are different - a group can both be paused and in error.

If in error, a group will stop it's current converge cycle, but any converging-action taken by the user (group config change, a policy execution, a scheduled policy execution, a request to the converge endpoint) will cause the group to converge again, which will either fix the group or leave it in ERROR again.

(Question: will adding the observer mean that changes to the tenant's servers also cause the group to converge if the group is in ERROR?)

If the group is paused, a group will actively prevent all future convergences and policy executions.  Scheduled policies will not execute.  Regular policies will not execute.  Changes observed by the observer will not cause a convergence (?).

I believe the outcome was:

1. Config changes will be accepted, but not acted upon (no converging)
2. Launch config changes will be accepted, but not acted upon (no converging)
3. Policy creations/deletions will be accepted, but not acted upon (no converging, no scheduled executions).

But please confirm the above 3 points.

Tasks:
- [ ] raise `CannotExecutePolicyError` when attempting to execute a policy on a paused group (this should cause the execute policy endpoint to 403)
- [ ] Return 403 on converge endpoint (only for convergence tenants) when attempting to converge a paused group
- [ ] New convergence cycles should abort if the group is paused
- [ ] After a convergence cycle ends, the dirty flag should be deleted if the group is in paused state (?)
- [ ] Integration test for pause: 
   - Once paused, executing a policy: 403
   - Once paused, hitting convergence endpoint: 403
   - Once paused, creating a scheduled policy works but it never runs
   - Once paused, changing the launch config and group config both work
   - Once paused, deleting the group also works (?)
   - Not sure what else, because it's hard to test that convergence stops, since it's hard to distinguish between convergence stopping and convergence not stopping but taking a really long time.

**Comment by cyli** [comment]
I don't think it's worth the existing convergence cycle, but pause should probably also delete the convergence flag?

**Comment by cyli** [comment]
Another question:  will we allow deleting the group if the group is paused?

**Comment by manishtomar** [comment]
> But please confirm the above 3 points.

+1

> but should pause delete the convergence flag so convergence doesn't continue?

Yes

> It seems like it won't be extra work so long as the contract can be: "Do not kill existing work - existing jobs will finish"?

Yeah. I am guessing the REST and scheduler can check if group is paused before continuing for all tenants. 

> will we allow deleting the group if the group is paused?

I don't see any issues with that. Force delete should always work.

**Comment by cyli** [comment]
From discussion on slack, if group is paused, no matter if there are servers:

- force delete should delete the group
- non-force delete should not delete the group

**Comment by manishtomar** [comment]
To clarify, we are not implementing this for worker as of now.

**Comment by manishtomar** [comment]
Currently, I am implementing this with existing field `GroupState.paused` which is returned in `../groupId/state` API as `{"state":{"paused": true, ...}}` . However, I think the right place for this is `"status": "PAUSED"` since in reality it is a state of the group just like ACTIVE and ERROR. However, doing this will cause confusion about "PAUSED" status and "paused" field. What do you all think?

**Comment by radix** [comment]
@manishtomar I'm not sure what confusion you're talking about. I think we should only have one thing indicating whether the group is paused in the REST result, if that's what you're talking about -- whether it's `"status": "PAUSED"` or `"paused": true` -- not both.

Or are you also taking about the data model in cass?

**Comment by cyli** [comment]
@radix:  I think he's talking just about the REST result.

Certainly `"paused": true` and `"status": "ACTIVE"` is confusing, so maybe just putting it in "status" is fine.

The two concerns I have are:

1. If we remove "paused", we'd be removing an existing field in the API (although it was never false, and never used, so dunno that it's super important, but pyrax for example may have issues)
1. Currently a group can be both in ERROR and paused, but if we do "status": "PAUSED", the user will no longer be able to tell if their group is in ERROR without looking at CF.  I don't know if this is a big issue though - maybe if the group is paused it doesn't matter if the group is in ERROR.

**Comment by radix** [comment]
Oh, I forgot about the existing `paused` field in the REST output.

Given that we are saving them as separate fields in our database, and it's possible for a group to both be paused and in error at the same time, I think we should represent that accurately to the user through the REST API, especially given we already have that `paused` field.

**Comment by manishtomar** [comment]
If the answer to the question "can the group be in ERROR _and_ paused" is yes then `paused` should be a separate field in API. However, I was not very sure about that. I think a group gone into ERROR can be paused at which time its status will be PAUSED and can become active only if user resumes it. But like @cyli said, the user will not know if their launch config was incorrect unless they look into cloud feeds. Also, having "PAUSED" status will required removal of existing field which can be problematic. I'll continue working on "paused" field. Thanks all for your comments :)

**Comment by manishtomar** [comment]
Closing since it has been implemented in #1646
