### ISSUE TITLE
Test converting worker groups to convergence groups

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1606]
We should create a bunch of groups with the worker, and in various states (maybe with some OOB changed servers), and ensure that converting the tenant to a convergence tenant does not break the groups.

Not sure how to easily automate this, since converting a tenant from a worker tenant to a convergence tenant involves a config change which requires a redeploy.

**Comment by manishtomar** [comment]
Notes on changed groups by testing on dev vm:
- get state returns empty active list and 0 `activeCapacity` but returns fine after triggering convergence. Policy executions are also fine.
- OOB deleted server on worker group. Changed it to convergence and triggered convergence. It got replaced with new server as expected.

**Comment by cyli** [comment]
@manishtomar Nice!!

**Comment by manishtomar** [comment]
I don't think any more testing should be required. Closing.

**Comment by manishtomar** [comment]
Reopening to test worker groups with CLB in it.

**Comment by manishtomar** [comment]
Scaling up and down a group with CLB works fine. The nodes are added and removed as expected and the group state returns correct _after_ triggering convergence.

**Comment by manishtomar** [comment]
Posted CLB results above. Closing.
