### ISSUE TITLE
delete/remove server from group broken in convergence

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#1624]
For convergence tenant when deleting server otter either removes AS metadata altogether (purge=false) or sets draining metadata (purge=true) and triggers convergence. Convergence gathering will not get updated metadata because it uses changes-since filter which doesn't return metadata updated servers. 

@cyli gave a wonderful idea to change server name when setting draining metadata to make changes-since work but I am not sure it will be acceptable for servers that are not being deleted (purge=false) since they will remain and customer may get confused seeing different name. We could actually change the name to something like `removing-oldname` and then immediately back to original name to avoid this problem. 

Another option could be to update metadata in the servers cache DB also along with updating the server but this can cause race condition between one node updating server info while converger node reading it mainly because the way converger updates the cache - by clearing all servers and inserting new ones. 

The only other option I can think of is to have some kind of dirty flag for these servers in a separate table that will be checked when gathering and got separately. I _think_ that does not have any race conditions.

**Comment by manishtomar** [comment]
Just realized that `DELETE serverId?replace=false` works because this removes otter metadata by using `PUT ../serverID/metadata` that updates `updated_at` instead of `PUT ../serverId/metadata/key` that doesn't. I think the easiest solution would be to change [`set_nova_metadata_item`](https://github.com/rackerlabs/otter/blob/master/otter/cloud_client.py#L737) implementation to use `PUT ../serverId/metadata`.

**Comment by cyli** [comment]
That's a great idea!  That is way better than the renaming because that is 2 requests that we have to keep consistent.  This way it's a single request that ensures the `updated` field is changed and also sets the metadata!  Thanks for figuring this out!

**Comment by cyli** [comment]
Looks like they also support POST (which takes a dictionary and updates the existing metadata instead of replacing the whole thing), but I'm not sure if it will update the `updated` field:  http://docs.rackspace.com/servers/api/v2/cs-devguide/content/MetadataSection.html

**Comment by radix** [comment]
@manishtomar That would work. It's not quite as nice since it means that there's a potential for race conditions where we overwrite other unrelated metadata values that are being added at the same time, but I think it's unlikely enough that we should still do it.

@cyli yeah if that works that would be better.

**Comment by manishtomar** [comment]
@radix Yeah. I agree with race conditions but not sure if there is anything better :/

**Comment by cyli** [comment]
If https://github.com/rackerlabs/otter/issues/1629 means we can't rely on changes-since, then maybe this is a non-issue.

**Comment by manishtomar** [comment]
If we completely avoid changes-since, then this is not an issue but we haven't concluded on that yet.

**Comment by cyli** [comment]
@manishtomar definitely, just wanted to link the two issues.  :)

**Comment by cyli** [comment]
Hmm... just sanity testing the POST vs PUT commands:

Created a server, waited until it was active:
```
{
  "server": {
    "status": "ACTIVE",
    "updated": "2015-07-29T21:06:10Z"
    ...
    "created": "2015-07-29T21:05:00Z",
    "metadata": {
      "build_config": "",
      "rax_service_level_automation": "Complete"
    }
  }
}
```

A few seconds later:

- `PUT /servers/<id>/metadata/whatsup  {"meta": {"whatsup": "done"}}`

    `GET /servers/details?changes-since=https://iad.servers.api.rackspacecloud.com/v2/898849/servers/detail?changes-since=2015-07-29T21:06:11Z`  ->  `{"servers": []}`

- `POST /servers/<id>/metadata  {"metadata": {"whatsup": "done2"}}`

    `GET /servers/details?changes-since=https://iad.servers.api.rackspacecloud.com/v2/898849/servers/detail?changes-since=2015-07-29T21:06:11Z`  ->  `{"servers": []}`

- `PUT /servers/<id>/metadata  {"metadata": {"whatsup": "done3"}}`

    `GET /servers/details?changes-since=https://iad.servers.api.rackspacecloud.com/v2/898849/servers/detail?changes-since=2015-07-29T21:06:11Z`  ->  `{"servers": []}`

I verified that the metadata had been changed at each point to by GET'ing the server.  :|

**Comment by manishtomar** [comment]
Did the `updated` field change after using any of the POST or PUT methods above?

**Comment by cyli** [comment]
@manishtomar didn't seem to :(  Possibly it's just being slow to update?

**Comment by manishtomar** [comment]
Closing since #1629 makes this a non-issues and it has been fixed.
