### ISSUE TITLE
NoSuchScalingGroupError unhandled deferred

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#1625]
We seem to be getting lot of `Unhandled error in Deferred: NoSuchScalingGroupError` errors in kibana. These occur when a deferred has errored and it has not been handled. These are logged by twisted when garbage collecting the deferreds. 

These are not harmful yet but may be hiding some bigger problem in the code somewhere.

**Comment by radix** [comment]
I think we may be able to track this down by recording tracebacks at time of verified_view and then running integration tests. still need to look a bit further into this
