### ISSUE TITLE
convergence view_state buggy?

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#1627]
`test_delete_server_not_found_in_diff_group` test in https://as-jenkins.rax.io/job/otter-cloudcafe-syd-convergence-system-tests/53/console failed because the group created with min entities 1 never showed 1 active server. But as per the [logs](https://dev-otterlogs.fedsso.rackspace.com/#dashboard/temp/adyJ8bTsTO-Hze8sFP0C3A), the server did become active and was updated in cache. But getting state on the group never showed the active server. 

I am not sure where the problem is. Did CASS didn't actually update it? Did the view state returned correctly but test didn't see it for some reason? The latter doesn't seem true since test logs shows otherwise. 

I am temporarily creating issue here for tracking purpose. Might debug if it occurs again.

**Comment by manishtomar** [comment]
@cyli pointed out that since delete and create are occurring very close in time, the delete could be taking precedence over create due to possible CASS clock drifts. The best way to overcome this is to add timestamps in the query. This is fine since cache is always inserted from same node. Thanks for the tip @cyli :D

**Comment by radix** [comment]
makes me wonder if we should be using counters instead of timestamps as the key for the servers cache...

**Comment by radix** [comment]
i.e., using counters may be more safe than timestamps even if we know we're always sending the commands from the same node. I guess it would look something like: get current highest counter, write new servers data with counter + 1. Maybe also include a UUID or timestamp per "batch" so we can disambiguate the pathological case of multiple concurrently-written batches with the same counter (arbitrarily choosing one UUID, or choosing the highest timestamp).
