### ISSUE TITLE
Logging responses

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1635]
There was some discussion about `logging_treq` logging responses for easier debugging in #1619 and #1629.

One requirement is that for otter prod, since we *definitely* need to not log some responses, or filter out some responses.  For instance, we do not want to log identity auth responses.  We don't want to log impersonation responses.  We do not want to log server root passwords when we create a server.  One suggestion from @glyph is that we encrypt all our logged responses, so we can't view them until there is some need to debug, but that might be pretty slow.

When discussing this more with @glyph and @radix, it turns out that we only want to log the success response, since APIErrors are already logged with bodies.  And we probably want to filter out certain JSON fields (like the password) and not just have a bunch of regexes.

`logging_treq` doesn't know about the content, it only logs the response itself.  `cloud_client` knows about all the different operations we're making, and what kind of data it should be getting back.

So 2 possibilities so far:

1. `cloud_client` does some extra logging of  filtered responses, in addition to the logging done by `logging_treq`.  This has the added bonus that we can truncate data (for instance, when listing servers we can log stats, and abbreviated server data, rather than a huge blob of all server details).

1. `logging_treq` automatically logs all responses, and filtering is done by matching the URL/method against regex, to determine what if any filtering is needed.  This can be done by our log observers, or by `logging_treq`.  This has the advantage of everything being logged, but that we have to re-constitute what operations are being performed (which `cloud_client` already knows) and what data needs to be synthesized given the response object and body.

`logging_treq` doing the logging also makes it usable by the trial tests.  On the other hand, we wanted to move toward using `cloud_client` on the trial tests anyway due to the retrying logic we already have in place with otter, and when hitting Mimic at least, we can instrument mimic to log all requests and responses.

**Comment by manishtomar** [comment]
I like 1. `cloud_client` functions can provide filters depending on the kind of requests it is making. The filters can be separately written functions in which one of them could be log everything that can be used by tests until it switches to `cloud_client`.

**Comment by cyli** [comment]
Sounds good.  :D  I'm leaning towards that.  I'm thinking:

- [ ] propagate the treq request ID as a header in all our requests?  I think that addresses part of #843, and then we can link the cloud client logs with the treq logs
- [ ] add a filtering and logging thing for create server
- [ ] move some of the gathering Nova functions to `cloud_client` and add logging for them too
