### ISSUE TITLE
ChangeCLBNode maybe should take an option to ignore errors

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1705]
When changing a CLB node due to self-healing, we definitely want the group to error if the CLB has been deleted.

But what about when we change a CLB node due to draining a server in preparation for it to be deleted?  Maybe that should be ok and we should just proceed.  Perhaps `ChangeCLBNode` should take an extra parameter that determines whether a CLB being deleted can be ignored.

**Comment by manishtomar** [comment]
I think its ok to put group in ERROR when draining a node results in CLB or Node not found errors. I think otter shouldn't try to be _too_ smart about things until requested. What do you think @radix?

**Comment by radix** [comment]
@manishtomar my thoughts reflect yours :) I agree that we should just do the simple solution until it's a problem.

**Comment by manishtomar** [comment]
Ok cool. Closing that is the current behavior.
