### ISSUE TITLE
Don't wait forever for servers to transition out of the `WAIT` destiny

### ISSUE THREAD

**Issue by radix** [rackerlabs/otter#1706]
From @manishtomar's review on #1702:

> I am worried about convergence running forever due to servers remaining in Destiny.WAIT forever. Honestly, I do not trust Nova to ensure servers will become normal. I think we should put the group in ERROR if Destiny.WAIT servers do not become ACTIVE within a certain time. It can be done in another PR though :)

I think the logic should be something like: if the only thing we're doing is waiting for servers in WAIT, and we do this for more than a certain period of time (either in terms of convergence iterations or real-time), stop iterating and put the group into ERROR.

**Comment by radix** [comment]
Idea: add a new `TEMP_RETRY` StepResult that signals that we should be retrying temporarily. If convergence detects that `>= N` retries have happened when the _only_ status was TEMP_RETRY, then put the group in `ERROR

**Comment by manishtomar** [comment]
Sounds good. Nitpick thought: how about naming it `LIMITED_RETRY` instead?
