### ISSUE TITLE
deleting node and server simultaneously

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#1714]
[CLB cafe test](https://github.com/rackerlabs/otter/blob/master/autoscale_cloudroast/test_repo/autoscale/system/integration/test_system_integration_lbaas.py#L244-L267) [failed](https://as-jenkins.rax.io/job/otter-cloudcafe-syd-convergence-system-tests/97/) because it expected nodes to get deleted _before_ server gets deleted as was the case with worker. However, convergence deletes server and corresponding nodes in same cycle. Mostly, nodes gets deleted first and the test passes but this time it deleted later than server and the test failed. 

Should the test expect the nodes to be gone after group state `activeCapacity` reflects that?

**Comment by radix** [comment]
I think it's reasonable to update the test to poll the LB nodes until it's deleted instead of assuming it'll already be gone.
