### ISSUE TITLE
New launch config type: launch_stack

### ISSUE THREAD

**Issue by dragorosson** [rackerlabs/otter#1726]
This launch config type will allow Heat stacks to be scaled. It really only consists of the request body that will be sent to Heat to do a stack create.

The properties that will be modified/added to `stack` will be
- `stack_name`, which will be need to be unique for each stack. If the user provides it, it can probably be used as part of the non-unique prefix.
- `tags`, which will need to include a tag so that Otter can list only the stacks that are tagged for the scaling group it's looking for. If the user provides tags, they will be included as well. Seems like there should be validation to reject tags that could conflict with the tag style Otter will use.

```
{
  "launchConfiguration": {
    "args": {
      "stack": { // same format as Heat stack-create expects
        "template_url": “https://foo.bar/baz.template”,
        // "template": “a template can be specified inline here in lieu of template_url”,
        "parameters": {
          "foo": “bar”,
          "baz": 5
        }
        // other parameters such as environment, files, etc.
      }
    },
    "type": “launch_stack”
  },
  "groupConfiguration": {
    // same as normal group configurations
  }
}
```

**Comment by radix** [comment]
Looks solid.

**Comment by manishtomar** [comment]
Closing.
