### ISSUE TITLE
New docs build platform -- how to build API developer guides in the api-docs folder

### ISSUE THREAD

**Issue by meker12** [rackerlabs/otter#1731]
Hello,

Today, I submitted a PR with an ``api-docs`` folder that contains a Sphinx documentation project to generate the Auto Scale API Developer Guide.  The content was migrated from the Dev Guide source in the ``docbook`` folder.  Starting September 29th, this content will be delivered to [developer.rackspace.com](https://developer.rackspace.com/) using the deconst publishing platform developed by the Rackspace Developer Experience team.  In early October, the Auto Scale documentation links on docs.rackspace.com will start redirecting to developer.rackspace.com. 

Here's are instructions for building the API documentation source in the api-docs folder.

**Build the Otter API documentation locally using Sphinx:**

- From the command prompt, run ```pip install Sphinx``
- Clone the Otter repo.
- Navigate to the file ``api-docs/rst/dev-guide`` folder.
- Run ``make singlehtml``.

**Build the Otter documentation locally using the deconst client application:**

With this option, you'll integrate the content with the Rackspace templates and branding so that it looks the same as it does when deployed to developer.rackspace.com.
- For instructions on installing and using the client, see https://github.com/deconst/client.
- If you run into issues with the client, log them in [deconst/client github issues](https://github.com/deconst/client/issues).

**Learn more about the new doc publishing platform**
  Rax.io Tech Talk:  Docs DeConstructed  
  September 22, from noon to 1:00 p.m
  Vidyo 4000035 // Austin RRR. 

 If you have questions or issues, Constanze can help or direct you to someone who can. 

Thanks!

Margaret Eker
Docs migration project lead

**Comment by manishtomar** [comment]
Closing as this is more of a wiki. Moved to https://github.com/rackerlabs/otter/wiki/Documentation-in-RST-format
