### ISSUE TITLE
"Create scaling group" API invalid link

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#1840]
The section https://developer.rackspace.com/docs/autoscale/v1/developer-guide/#create-scaling-group
appears under "Create and manage scaling groups". When "Create scaling group" section under "API Reference" is clicked, it jumps to that section. This is because both the sections have same anchor `#create-scaling-group`. Kindly fix this by changing the anchor of any one of them. @stanzikratel could you help with this?

**Comment by meker12** [comment]
Fixed in https://github.com/rackerlabs/otter/pull/1841
