### ISSUE TITLE
CLB node gets added before application in server is ready

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#1870]
When a server becomes ACTIVE, it is immediately added to CLB. During this time, the application in server that is serving the port is mostly not yet ready and this results in various errors like 503s or 404s or "welcome to apache" depending on what situation the web server is in. This can be avoided by doing the following:

1. Add a node with a “DRAINING” condition. It should be pulled into rotation except that no new connections can be established.
2. Wait for the health checks to complete (depends on the health check parameters) at which point the status of the node will either be “ONLINE” or “OFFLINE”.
3. Change condition to “ENABLED”. If status is “ONLINE” the node will start to receive traffic. If status is “OFFLINE” the node should not serve traffic. If status is “OFFLINE” health check will eventually change status to “ONLINE” once it deems the node healthy. 

Following are possible changes to be done in convergence:

1. When server's node is not found, create new node in `DRAINING` if health check is enabled on the CLB. If not, add it as `ENABLED`.
2. When it notices that a node exists but is in `DRAINING`, it will check whether corresponding server's [`DESTINY`](https://github.com/rackerlabs/otter/blob/21cd1b150e67923a6b3db2d78f22d94565fa4dfd/otter/convergence/planning.py#L311-L316) is to drain. If so, it will continue to drain as usual, otherwise it will assume that it is new node that needs to be `ENABLE`ed. It will `ENABLE` the node if node's status is `ONLINE`. Otherwise, return RETRY. It is possible that node may never go `ONLINE` in which case we should put group in ERROR if it remains OFFLINE for > timeout (1 hour). This can be done by checking node's created time with current time. Created time can be got from node feed.

One of the problems with above changes is that it is CLB specific and the planner is generic using `ILBDescription` and `ILBNode` interfaces. Granted that all this will be done only if `ILBNode` implements `IDrainable` which currently is only CLB but is a problem if another LB type (RCv3) implements `IDrainable`. We could try to structure this part in seperate CLB specific functions.

**Comment by manishtomar** [comment]
@glyph Not sure if you are following the as-dev mails but would like your opinion on above.

**Comment by glyph** [comment]
I love the naming for `Destiny`, first time encountering that :).

The "health check" here is the LB's ["health monitor"](https://developer.rackspace.com/docs/cloud-load-balancers/v1/developer-guide/#show-health-monitor-configuration), yes?

It took a while for me to completely understand this, so I'm curious as to how you're going to document it.  Would something like this be accurate?

> When health monitoring is enabled on a load balancer, newly created servers will not be added to your load balancer until their health check is successful.

My understanding is that the _reason_ to put the server into `DRAINING` initially is that if you were to put it into ACTIVE, it would immediately start handling requests, and then keep trying to handle requests until you exceed `attemptsBeforeDeactivation`, which would provide a window for users onto a partially functional service during scale-up just like there is now.

If my understanding is correct, this sounds like a great plan.

**Comment by manishtomar** [comment]
> The "health check" here is the LB's "health monitor", yes?

Yes.

> When health monitoring is enabled on a load balancer, newly created servers will not be added to your load balancer until their health check is successful.

Perfect.

> My understanding is that the reason to put the server into DRAINING initially is that if you were to put it into ACTIVE, it would immediately start handling requests, and then keep trying to handle requests until you exceed attemptsBeforeDeactivation, which would provide a window for users onto a partially functional service during scale-up just like there is now.

Yes.

> If my understanding is correct, this sounds like a great plan.

Cool. Thanks :) Will start working on it.

One of my concerns was this behavior is CLB specific but planner is generic. Let me see if can be structured separately in code.

**Comment by glyph** [comment]
> One of my concerns was this behavior is CLB specific but planner is generic. Let me see if can be structured separately in code.

Presumably you could just have an `IHealthMonitor` implementation for RCv3 LBs that just says "nope, health monitoring enabled"?

**Comment by manishtomar** [comment]
> Presumably you could just have an IHealthMonitor implementation for RCv3 LBs that just says "nope, health monitoring not enabled"?

This would mean any LB that has health monitor should do the above dance which I am not sure is a good idea since its basically workaround for the way our CLB works. However I like the idea of using an interface to describe this behavior. How about `IAddNodeAsDraining` (not a good name)?

**Comment by glyph** [comment]
> This would mean any LB that has health monitor should do the above dance which I am not sure is a good idea since its basically workaround for the way our CLB works. However I like the idea of using an interface to describe this behavior. How about IAddNodeAsDraining (not a good name)?

Huh.  Adding the node in a draining state is just as specific to our CLB as the health monitor check though, isn't it?  i.e. a better load balancing system (and perhaps some future CLB version, as well) would just do this automatically as part of `add` if you had a health monitor enabled?

**Comment by wirehead** [comment]
That is very much specific to the present Rackspace LB version, yes.

**Comment by manishtomar** [comment]
> Huh. Adding the node in a draining state is just as specific to our CLB as the health monitor check though, isn't it?

I don't think so.

> .e. a better load balancing system (and perhaps some future CLB version, as well) would just do this automatically as part of add if you had a health monitor enabled?

Yes. Basically having a health monitor does not correlate to adding the node as draining.

**Comment by waveywhite** [comment]
Can the node simply be added to the load balancer in an "automatically disabled" state, if the load balancer has health monitoring?

**Comment by manishtomar** [comment]
> Can the node simply be added to the load balancer in an "automatically disabled" state if the load balancer has health monitoring?

@waveywhite Unfortunately, this is not true with CLB. CLB currently adds a node in ENABLED/ONLINE state even if health monitor is enabled. It's after some number of seconds depending on health monitor config the node becomes OFFLINE which unfortunately is too late for most applications. This whole issue wouldn't exist and we wouldn't be talking if CLB behaved the way you mentioned :)
