### ISSUE TITLE
LockTimeouts :(

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#1915]
One tenant is constantly getting locktimeouts when calling webhook 3 times simultaneously. Need to debug and see where is the problem in Kazoo. I've been failing to reproduce this on my dev env.

**Comment by manishtomar** [comment]
After extensive debugging, I found at least one problem. Lock release deletes child ephemeral znode which triggers watch event on the previous caller who is waiting to acquire the lock. On receiving the event, that caller must wake up and try the acquiring process again: i.e. get the children and see if's created child is the smallest. THIS does not happen. After receiving the watch event the caller wakes up after some extra time (in my case 22 seconds!) to check if it has the lock. 

[This](https://github.com/python-zk/kazoo/blob/2.2.1/kazoo/recipe/lock.py#L236) is where the watch is set and next line should unblock on getting the event continuing the while loop which doesn't happen. 

I am not sure if this could be due to twisted threadpool. @glyph What do you think? Any remote chances? Please note that `self._watch_predecessor` is called from events callback thread that is created [here](https://github.com/python-zk/kazoo/blob/2.2.1/kazoo/handlers/threading.py#L116-L120) in beginning of the application.

**Comment by glyph** [comment]
I've been looking at this ticket for the last few days without coming to any specific conclusion.  This does indeed look complex.

The only contribution I could think of that the Twisted threadpool *might* have is that it sets a fairly conservative maximum number of threads.  In some cases this can provoke deadlocks.  For example:

Let's say you have a thread-pool with a limit of 4 threads maximum.  Some other part of your application starts 2 long-running tasks.  Your code, knowing that the limit is 4, starts 3 parallel tasks which all wait on a lock.  Then it fires up a 4th task to release the lock.  That 4th task will wait in line forever, never being run; your threadpool is now wedged forever.

I think that having a fixed maximum size for a threadpool is actually a design error.  This is a ticket in Twisted for addressing this problem: https://twistedmatrix.com/trac/ticket/5298

**Comment by manishtomar** [comment]
Not sure if it helps but I've seen the number of threads be much less than max threads in production. Max is set to 110 and I've seen sometimes 23 sometimes 53 threads when this problem is occurring.

**Comment by glyph** [comment]
Hmm.  OK, that seems unlikely then.  If the Twisted threadpool is not wedged on thread-creation, there are not a lot of other places it can go wrong…

**Comment by glyph** [comment]
This isn't around startup or shutdown, right?  Just doing normal operation?

**Comment by manishtomar** [comment]
> This isn't around startup or shutdown, right? Just doing normal operation?

Yeah.

**Comment by glyph** [comment]
For now I think we can rule out the Twisted threadpool as a culprit then, at least conditionally…
