### ISSUE TITLE
One CLB write call per convergence cycle

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#1939]
If planner returns multiple types of steps w.r.t a CLB (like add AND delete nodes) then otter calls them concurrently causing CLB to go into ERROR sometimes. The chances increase if there are many nodes involved in the call. 

This can be fixed if steps transformer allows only one mutating call per CLB since it any mutating call results in PENDING_UPDATE state which stays for a few seconds. Next convergence call can take care of other mutating calls.

**Comment by glyph** [comment]
Has this been reported upstream with the CLB service itself?  It seems like concurrent invocations should not *break* a CLB.

**Comment by manishtomar** [comment]
> Has this been reported upstream with the CLB service itself?

Yes. They are tracking it at https://jira.rax.io/browse/CLB-161

**Comment by glyph** [comment]
Thanks for the reference.
