### ISSUE TITLE
Delete and Detach functional testing

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#764]
The detach feature needs functional tests.

Specifically, we need a test that detaches a server (a.k.a remove with detach in the API), and then asserts that:

1. The server was not deleted from Nova.
1. The server was removed from all its load balancers.
1. The otter-specific keys in the server's metadata are removed. The interesting function to look at for that is [`scrub_otter_metadata`](https://github.com/rackerlabs/otter/blob/master/otter/worker/launch_server_v1.py#L660).

**Comment by cyli** [comment]
The deletion scenarios are covered by 

https://github.com/rackerlabs/otter/blob/master/autoscale_cloudroast/test_repo/autoscale/system/group/test_group_servers.py

#1699 Should cover the detach feature

**Comment by manishtomar** [comment]
Closing as fixed in #1699
