### ISSUE TITLE
RackConnectV3 Integration Testing

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#793]
Create a set of tests for RackConnect V3

Tasks:
- [ ] 1.) Create configuration to run against RackConnect account
  - [ ] 1a) Document new config file elements and the changes made to support them
        (In elaboration comment - list new values, their default values and dependencies) 
         ex. rcv3_cloud_network, default not present, add to config.py and fixtures.py) 
  - [x] 1b.) Create config file for Mimic
  - [x] 1c.) Create config file for Hardware
  - [ ] 1d.) Add config file generation to autoscaling-chef
  - [x] 1e.) Modify autoscale cloudcafe to read in new config values

- [ ] 2.) Implement RCV3 API client in autoscale_cloudcafe
  *RackConnect API methods to implement*
  - [x] 2a.) List all load balancer pools on the account
    - [x] RackConnectLBPool response object and marshalling
    - [x] RackConnectLBPools response object and marshalling
  - [x] 2b.) Get info on a specific LB Pool (uses RackConnectLBPool response object)
  - [x] 2c.) List nodes on a LB Pool
    - [x] RackConnectLBNode response object
    - [x] RackConnectLBNodes response object
  - [x] 2d.) Get Node Info Detail  - This is a superset of Get Node Info
    - [x] Add response objects
  - [x] 2e.) Remove Node
    - [x] TBD request/response objects
  - [ ] 2f.) _Get Node Info [Optional]_ This is not likely needed since all info is also in detail view
  - [ ] 2g.) _List Nodes with detail [Optional]_ We shouldn't need any of the detail info for testing
  - [ ] 2h.) _Add Node [Optional]_ Not needed for testing at this scope

- [ ] 3.) Test Cases

*Create Group*

- [x] 1.) Create group with the following:
        - min_entities = 0
        - Single RackConnectV3 type load balancer with valid pre-created pool_id
        - RackConnect internal network only

        Verify:
        - Create status is OK
        - Create response is 201
        - launchConfig for the group contains the correct LB uuid & type

- [x] 2.) Create group with the following:
        - min_entities = 1
        - Single RackConnectV3 loadbalancer with valid uuid
        - RackConnect internal network only

        Actions:
        - In setUp - get initial node_counts on lb pool
        - wait for expected active servers (OR) FAIL
        - get current node_counts

        Verify:
        - verify cloud_server node count increased by one
        - verify total count increased by one
        - verify external count did not change

- [x] 3.) Create group with the following:
        - min_entities = 1
        - Single valid RackConnectV3 loadbalancer
        - RackConnect internal network, public network, private network (ServiceNet)

        Actions:
        - wait for expected active servers (OR) FAIL
        - get nova_server_id of server on group

        Verfiy:
        - assert nova_server_id is in list of servers on node (helper function)
        - verify correct networks are present on server
        - verify correct lb_pool node status (ACTIVE?) (what are other status options?)

- [x] 4.) Create group with the following:
        - min_entities = 1
        - valid RackConnectV3 loadbalancer, valid CLB
        - RackConnect internal network, public network (maybe not needed?), private network (ServiceNet)

        Actions:
        - wait for expected active servers (OR) FAIL
        - get nova_server_id of server on group

        Verfiy:
        - assert nova_server_id is in list of servers on pool node (helper function)
        - assert nova_server_id is on CLB node
        - verify correct networks are present on server
        - verify correct lb_pool node status (ACTIVE?) (what are other status options?)

*Update launchConfig*

- [ ] 5.) Update launchConfig to add CLB (will be altered by convergnece)
        Initial State:
        - Scaling group with min_entities > 0, single rcv3 lb, internal & private network
            -- Note: CLB requires private network - similar cases with only internal/public should be added as negative cases

        Steps:
        - wait for expected number of active servers
        - Get active server list after creation
        > verify rcv3 lb has active server(s) as nodes
        - Update launch config to add a CLB
        - Add and execute scaling policy to scale up by 1
        - wait for expected number of active servers
        - get list of server(s) added by scaling operation
        > verify CLB & rcv3 lb have added server(s) as nodes

- [ ] 6.) Update launchConfig to add second rcv3 lb_pool (will be altered by convergnece)
        Initial State:
        - Scaling group with min_entities > 0, single rcv3 lb, internal & private network
            -- Note: CLB requires private network - similar cases with only internal/public should be added as negative cases
            -- rcv3 pool with multiple internal networks is unknown behaviour - confirm expected then add as positive/negative as appropriate

        Steps:
        - wait for expected number of active servers
        - Get active server list after creation
        > verify rcv3 lb has active server(s) as nodes
        - Update launch config to add second rcv3 pool
        - Add and execute scaling policy to scale up by 1
        - wait for expected number of active servers
        - get list of server(s) added by scaling operation
        > verify both LB pools have added server(s) as nodes

- [ ] 7.) Update launchConfig to add rcv3 pool to group without LB (will be altered by convergnece)
        Initial State:
        - Scaling group with min_entities > 0, no load balancer, internal & private network

        Steps:
        - wait for expected number of active servers
        - Get active server list after creation
        - Update launch config to add rcv3 pool
        - Add and execute scaling policy to scale up by 1
        - wait for expected number of active servers
        - get list of server(s) added by scaling operation
        > verify LB pool has added server(s) as nodes

- [ ] 8.) Update launchConfig to replace CLB on group with rcv3 pool (will be altered by convergnece) - Do we also need a case of replacing rcv3 with a different rcv3?
        Initial State:
        - Scaling group with min_entities > 0, single CLB, internal & private network

        Steps:
        - wait for expected number of active servers
        - Get active server list after creation
        - Update launch config to add rcv3 pool
        - Add and execute scaling policy to scale up by 1
        - wait for expected number of active servers
        - get list of server(s) added by scaling operation
        > verify LB pool has added server(s) as nodes and CLB does not

- [ ] 9.) Update launchConfig to remove rcv3 pool from group (will be altered by convergnece)
        Initial State:
        - Scaling group with min_entities > 0, single rcv3 lb, internal & private network

        Steps:
        - wait for expected number of active servers
        - Get active server list after creation
        - Add and execute scaling policy to scale up by 1
        - Update launch config to remove rcv3 pool
        - Add and execute scaling policy to scale up by 1
        - wait for expected number of active servers
        - get list of server(s) added by scaling operation
        > verify that added server(s) are not in the rcv3 pool nodes
        - create and execute policy to scale down by 2
        > verify servers on pool match list after creation (assumes newest removed first)

*Scaling Operations*
- [ ] 10.) Scale up and down  (Split into three test cases)
        For each of the following configurations:
  - [x] Scaling group with 1 min_entities, single rcv3 lb, internal & private network
  - [ ] Scaling group with 1 min_entities, two rcv3 lbs, internal & private network
  - [x] Scaling group with 1 min_entities, rcv3 lb & CLB, internal & private network

        Steps:
        - Get initial nodes on each of the group's load balancers after group creation
        - create and execute policy to scale up by 1
        - wait for expected number of active servers
        - get list of servers added by scaling operation
        - verify initial nodes on all LBs were unchanged
        - verify servers added by scaling up are present on all LBs
        - Create and execute policy to scale down
        - verify that the initial nodes were unchanged by the scale down operation
        - verify that the servers added by scaling up were removed (Assumes that newest servers are removed first)

- [ ] 11.) [Robustness] - Scale down server that was manually removed from rcv3 loadBalancer
Initial State:
        - Scaling group with min_entities = 0, single rcv3 lb, internal & private network

        Steps:
        - create and execute policy to scale up by 1
        - Get active server list after creation
        - Confirm server added by scale was added to LB as node
        - Through RCV3 API, remove server node from pool
        - Create and execute policy to scale down
        > verify server deleted from group & Nova
        - get list of server(s) added by scaling operation
        > verify LB pool has added server(s) as nodes and CLB does not

*Negative*
- [ ] 12.) [Negative] - Create group with invalid rcv3 lb
        - min_entities = 1
        - Invalid RCV3 load balancer - (various)
        - RackConnect internal network, private network (ServiceNet)

        Actions:
        - _wait_for_servers_to_be_deleted_when_lb_invalid (see lbaas tests)

        Verify:
        - servers successfully deleted from nova & group

From LBAAS tests: (add to list of cases later?)
test_force_delete_group_with_load_balancer
test_delete_group_when_autoscale_server_is_the_last_node_on_lb
test_group_with_invalid_load_balancer_among_multiple_load_balancers

Not now:
test_load_balancer_pending_update_or_error_state

**Comment by radix** [comment]
There are a number of error conditions we handle when removing nodes from RCv3 load balancers - it doesn't look like these are tracked, so here they are:

- upon removing multiple nodes (from potentially multiple different pools),
  - if only one node is not a member of a pool, otter will retry with just the valid nodes/pools
  - if only one pool does not exist (but others do), otter will retry with just the valid nodes/pools
  - if only one pool is inactive (but others are fine), otter will retry with just the valid nodes/pools

**Comment by kivattik** [comment]
This issue is being closed with the conclusion that the existing tests in test_system_integration.py are sufficient to allow deployment of RCV3. Additional cases will be documented individually and added to the QE backlog. #1308
