### ISSUE TITLE
convergence.Request should specify retry logic

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#805]
Right now, convergence.Request has no way to specify retry logic. This might be fine: you can just go ahead and retry convergence if anything fails. However, this means making a ton of extra requests to upstream services, and we try to be nice about not hammering their API :) Plus, it makes sense to try and execute a plan to the fullest: we've just computed that this is what we need to do, the least we can do is retry to fix transient failures in executing it :)

Retry logic should decouple "can I retry" from the actual retrying policy (e.g., 5 times starting at two seconds with exponential backoff). This is so we don't run into the issue of every retrying call site specifying its own little bespoke artisanal handrolled retrying policy (see #791).

Steps to resolve:

- [ ] Solve #791 as specified on that ticket (add a default to [`retry_effect`](https://github.com/rackerlabs/otter/blob/master/otter/util/retry.py#L351)).
- [ ] Add a `can_retry` function (`Failure -> bool`, just like the one `retry_effect` takes) attribute to `convergence.Request`. By default, this is `None`.
- [ ] Add support for this to `convergence._conv_reqs_to_effect`: create the usual create-a-request effect, inspect the `can_retry` attr. If it's `None`, just use the effect verbatim; if not, wrap it with [`retry_effect`](https://github.com/rackerlabs/otter/blob/master/otter/util/retry.py#L351)

**Comment by radix** [comment]
convergence.Request is gone now, and steps can specify their own retry logic in as_effect, so I'm closing this as invalid. Some discussion here: https://github.com/rackerlabs/otter/pull/943#issuecomment-71080192
