### ISSUE TITLE
Add support for cloud metrics service in `otter.http.get_request_func`

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#810]
- [x] first add Cloud Metrics support to get_request_func (or ServiceRequest)
- [x] then use it in add_to_cloud_metrics

This has 2 advantages:
- The token is cached like other services, above function doesn't need to auth every minute reducing load to identity
- The above function uses effect making it pure and easily testable.

**Comment by radix** [comment]
Sorry, I was confused about the status of this ticket and made some changes that I shouldn't have made. I'll try to revert them and mark it as closed.
