### ISSUE TITLE
RackConnectV3 convergence

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#821]
Handle RackConnectV3 load balancer pools in convergence. This can be split up in following tasks:
- [x] Define model to represent RC3 LB pool and its nodes
- [ ] Gather RCv3 load balancer pools and nodes in above model 
- [x] Take it as input to `converge` and return steps needed to add it to the pool
- [x] [Update _lb_configs_from_metadata](https://github.com/rackerlabs/otter/pull/1102#discussion_r24850105)

**Comment by lvh** [comment]
We could really use these model types for building integration tests.

**Comment by lvh** [comment]
I added the [Update _lb_configs_from_metadata](https://github.com/rackerlabs/otter/pull/1102#discussion_r24850105) requirement to the description.

**Comment by lvh** [comment]
On second thought, this ticket probably shouldn't exist. There's a milestone for that. I'll rip the requirements apart and turn them into separate tickets.
