### ISSUE TITLE
add_bind_root randomly coerces to bytes with utf-8 and ascii

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#827]
Figure out which one it has to be and why, or why we even have to do this right now. Maybe a better resolution would be to not stuff unicode in?

Original ask: https://github.com/rackerlabs/otter/pull/822#issuecomment-66709604

Code got copied a bunch of times, no-one remembers why, so the answer is probably "totally arbitrarily".

I think it should probably be ascii, I don't know if everything down the chain knows about punycode, and if it does, it should probably be taking `unicode` not `str`.

**Comment by lvh** [comment]
I don't quite get why this can be either type.

Either the thing called `url` is really a URI, which is really a URI, which [RFC 3986](http://www.ietf.org/rfc/rfc3986) feels pretty strongly is a sequence of fairly boring characters. However, the RFC explicitly specifies that this is not necessarily a sequence of octets, so, probably the appropriate Python type is `unicode`, not `str`. (2.8!)

So, then we have hosts, and we have paths. Hosts are easy; Punycode has won. Paths, well, with paths, we get a bit more wiggle room.

However, at the end of the day, `Agent` doesn't do IRIs, and therefore neither does `treq`, and therefore neither do we. Hence, `otter.test.util.test_pure_http.BindRootTests.test_url_unicode` is arguably a bad test.

#888 takes a little step through Unicode and then always encodes to UTF-8. It makes the tests pass, which I'm not sure is desirable, but it does technically address this issue.

**Comment by radix** [comment]
Some day, far in the future, we'll use fxhttp (which only kinda exists right now), which will use URLObject, which has a "from_iri" method, which I implemented a while back in https://github.com/zacharyvoase/urlobject/commit/a2bb7ebf056005d373e7f677dc7828a22eb5b8fa

Until then, I think your PR looks good.

**Comment by lvh** [comment]
Okay, great. Do you think this ticket should stay open, or a new one should be created, or is fxhttp just going to kind of happen?

**Comment by radix** [comment]
I think #888 sufficiently resolves this issue for otter's purposes, so I think this ticket should probably be closed once it's merged.
