### ISSUE TITLE
(EST 1) Rename network names from public and private to avoid known bugs with Otter

### ISSUE THREAD

**Issue by sam-falvo** [rackerlabs/otter#828]
To avoid confusion:
- In RCv3 tests only; other tests hard-wire constant names, and not our concern
- [ ] Rename public to service_net
- [ ] Rename private to internal_net

**Comment by sam-falvo** [comment]
As I recall, this was a code review comment you spoke to us about concerning variable names.  E.g., we weren't going to change the actual test names as passed over the wire; rather the variable names relevant to these networks in the tests themselves.  If this is no longer an issue, let me know, so I can close the ticket.  Thanks!

**Comment by lvh** [comment]
Yes, this is about changing the variable names in the tests; it just isn't about a bug in otter :-)
