### ISSUE TITLE
Implement function that retries convergence until done

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#844]
#817 gives us a clean function for a single convergence cycle: gather -> plan -> effect. We additionally need something that tries to converge until the plan is empty, or until an unrecoverable error occurs.

This probably needs #818 to be particularly successful.

**Comment by lvh** [comment]
I should clarify: `ConvergeLater` would still be valuable, potentially, as a hint towards how much you should wait before retrying. However, that's very definitely not a blocker; for now we can just retry with fairly lengthy times in between.

If the times are sufficiently lengthy, this might provide an answer to the conundrum we had on #866 with respect to how to implement request-level throttling.

**Comment by lvh** [comment]
The effect-wrapped bool returned by `execute_convergence` specifies if you should retry or not. That bool really just checks if the list of effects that were parallel-executed is empty or not, so currently the semantics are "empty plan means you're done". So, it looks like we need to implement `ConvergeLater` no matter what.

**Comment by manishtomar** [comment]
+1 on `ConvergeLater`

**Comment by lvh** [comment]
Cc @radix.

One of the arguments to `execute_convergence` is the desired state of the world. When repeatedly executing convergence, we should try to get a new version of the desired state of the world in between `execute_convergence` runs. After all, if a customer is at 10 machines, asks for 100, we bring them up to 20 and then they ask for 50 instead, we shouldn't gradually take them to 100; we should stop when we hit 50.

This means that the real thing that we're retrying is a combination of:

1. Get the new desired state.
2. Execute convergence to attempt to reach that state.

Since our fancy retry logic takes effects, that means that there should be an effect for doing both of these steps that take the same argument as the relevant functions. So:

1. An intent `GetDesiredState`
2. An intent `ExecuteConvergence`

How do I combine these intents into a single effect?

**Comment by radix** [comment]
Ah, I see.

That would just be: `Effect(Func(get_desired_state)).on(execute_convergence)`.

For the record, you don't actually need to make these things specific intents. As my code example shows, your "get desired state" step can just be a Func intent calling get_desired_state. And ExecuteConvergence is just what our execute_convergence function already returns. Not that making them intents is bad.

**Comment by lvh** [comment]
And, to be clear, that'd be an effect of bool, right? (Well, effect of `X`, where `execute_convergence` returns an effect of `X`).

**Comment by radix** [comment]
yep. in order to get that to work with the retry machinery, you could add another callback that raises an exception when the result is True.

(the retry machinery in Effect could probably be generalized to work on arbitrary results instead of only on exceptions...)

**Comment by manishtomar** [comment]
Getting group desired state involves asking desired and launch config from Cass. Few ways we can use effect is:
1. Have `GroupModelRequest` intent that contains `tenant_id`, `group_id`, `request_func_name` and `args`. This intent when performed will have the `CassScalingGroupCollection` object with it and call the given function on the object. This intent can then be used to get desired (the model should have a new method `get_desired` to fetch desired) and launch_config via `view_launch_config`. 
2. Have a `CQLQuery` intent that gets returned when implementing new `get_desired` method. A new method `view_launch_config_effect` can be implemented that returns the above intent. This is because `view_launch_config` is an existing method and it would be undesirable to change its signature. 

Also, why does `get_desired_state` need to worry about retries? The retry is only used when performing steps.

**Comment by lvh** [comment]
`get_desired_state` retrying is just about recovering from transient Cassandra failures, which might not be necessary The retrying we're talking about is about the *composition* of `get_desired_state` and `execute_convergence`.

**Comment by lvh** [comment]
I think this is currently blocked on #956, kinda.

**Comment by radix** [comment]
sorry for all the milestone spam. turns out this change _isn't_ necessary for "1 integration test", as `test_system_server_details_name_and_metadata` passes without it.

**Comment by radix** [comment]
This was fixed with #1219.
