### ISSUE TITLE
Poll until resource deletion is confirmed

### ISSUE THREAD

**Issue by sam-falvo** [rackerlabs/otter#855]
As one test finishes, another starts up, even though the resources created in one test aren't fully disposed of yet.  This affects, in particular, the `test_create_scaling_group_with_pool_counts` test.

First and foremost, I need to check for server deletion, I *think*.  But, other kinds of resources may be required.  Further testing is required.

**Comment by cyli** [comment]
@sam-falvo Is this issue complete?
