### ISSUE TITLE
Throttling

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#866]
We need to implement throttling.

The primary throttling method suggested by upstream is to stagger requests per service and per region. (However, the only service we really have to care about is compute; all of our other requests are pretty speedy.)

For example:

1. Issue a server creation request.
2. Wait *n* seconds.
3. Issue another server creation request.
4. Wait *n* seconds.
5. ...

In the long run, we should be able to throw as many requests out as we'd like. That requires solving a much harder problem upstream. Since we should be able to throw out the throttling eventually, it's important to pick composable abstractions, because it will be easier to excise them later.

**Comment by lvh** [comment]
Cc @radix: I'd love to hear your thoughts on where you feel the request-level throttling fits best in effect. Maybe a queue that gets some effects pushed on it? Wrapping everything with another effect seems suboptimal; how would they coordinate with each other re: delays? What's the effect version of a DeferredSemaphore? (Does effect even really help much here, since you've already decided you want to do this thing?)

**Comment by radix** [comment]
I don't think you need anything like DeferredSemaphore. The simple thing to do for serial request throttling would be to just add a callback which returns a Delay Effect, with its own callback that returns the next effect in the series (and then another callback to combine the two results so you don't lose them). And fold it!

So, if you have a list of effects that you want to perform serially and with a delay in between, you write this (sadly this is longer than I had hoped):

```python
def throttle(interval, effs):
    def folder(cumulative_effect, next_effect):
        return cumulative_effect.on(lambda r:
               Effect(Delay(interval)).on(lambda ign:
               next_effect.on(lambda r2: r + [r2])))
    first = effs[0].on(lambda r: [r])
    return reduce(folder, [first] + effs[1:])
```

There's some annoying bookkeeping around trying to accumulate the results into an ordered list. I feel like I may be missing a more concise solution there. I probably need to start writing a little library of Effect combinators...

Varying but pure intervals are left as an exercise for the implementer :) It could be as simple as generating a list of jittered intervals up-front.

**Comment by lvh** [comment]
I'm not sure I understand: doesn't that assume the list of effects is known up front? I'm trying to do node-global throttling, so effects can come in while this delay process is already underway.

**Comment by radix** [comment]
Ah, I see. I'll think about it some more.

**Comment by lvh** [comment]
It might be useful to have a reasonable way to express randomized throttling in both worker and convergence, which would probably mean a treq wrapper.

**Comment by lvh** [comment]
`_perform_limited_effects` already does something kind of similar thing, but also assumes that you know all the requests up front. Perhaps a `FuncIntent` that just consumes something off a `DeferredQueue` would be a reasonable intermediary. For now, I could just hack it together the usual way, and write it as a function wrapper. That way we just need to apply it all the way down in the treq function that actually makes the requests. Maybe it could be implemented as a scope; I'll have to think about that one for a bit.

**Comment by manishtomar** [comment]
How about a generator that generates effects on-the-fly? This can be given to effect-throttler (if there can be such a thing). This is similar to how `coiterate` does throttling.

**Comment by lvh** [comment]
How does the generator solve the problem of having to know the effects up front? Where does the generator get the effects?

**Comment by manishtomar** [comment]
You generate effects on need basis. Wasn't that the problem asked earlier? "doesn't that assume the list of effects is known up front? I'm trying to do node-global throttling, so effects can come in while this delay process is already underway." It looked like you don't want/have the effects upfront.

**Comment by lvh** [comment]
Yes, that's what we're trying to do. We don't have the effects up front; the effects are produced at some later point in time. The effects are a consequence of trying to do some convergence; we can't just decide to do some computation and end up with some effects. Therefore, a queue solves this problem: you can put things in a queue. But how do I "generate effects on need basis"?

**Comment by manishtomar** [comment]
> But how do I "generate effects on need basis"?

I am not sure how to do this w.r.t convergence. I was just pondering a possible solution for the problem of "I don't have all the effects upfront". 

Also, doesn't step-level throttling give just the right amount of effects? So, is effect-level throttling really required?

**Comment by lvh** [comment]
The argument for both step-level and request-level throttling is made earlier in this ticket. They address different use cases. As I mentioned in previous standup, yes, I have a hunch that step-level throttling might just be enough, but only because the dimension that request-level throttling is trying to optimize along isn't unambiguously "slower is less load", due to (hypothetical) caching effects.

**Comment by lvh** [comment]
I'm going to close this based on the assumption that the step limiting introduced by #939, in combination with the repeated convergence thing of #844 solves this satisfactorily; otherwise, we can re-open.
