### ISSUE TITLE
converge should prepare launch config

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#883]
Each `CreateServer` step returned from `converge` should have launch config that corresponds to  [`otter.worker.launch_server_v1.prepare_launch_config`](https://github.com/rackerlabs/otter/blob/master/otter/worker/launch_server_v1.py#L555)

**Comment by lvh** [comment]
Looks like we can probably just copy that function over to a place in convergence?

**Comment by manishtomar** [comment]
Probably. However to ensure purity of `converge` I was thinking having uuid implementation be part of `DesiredGroupState` which will have real world implementation when running as a whole and dummy implementation during tests. Will think about it some more.

**Comment by manishtomar** [comment]
I am working on this.

**Comment by radix** [comment]
Name generation, which is the hard part of this (since it's side-effectful) has been resolved with #930. The only other important piece of metadata that I'm aware of is rax:auto_scaling_group_id, which we use during gathering to discover the correct servers for a group. I'll do a PR to add that.
