### ISSUE TITLE
iso8601 dependency can't be upgraded because bogus test times

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#891]
Some of the dates we use are no longer supported by the current version if iso8601; according to the standard, arguably correctly:

```
[ERROR]
Traceback (most recent call last):
  File "/Users/lvh/Code/rackspace/otter/otter/test/test_supervisor.py", line 492, in test_returns_oldest_servers
    3),
  File "/Users/lvh/Code/rackspace/otter/otter/supervisor.py", line 277, in find_servers_to_evict
    sorted_servers = sorted(state.active.values(), key=lambda s: from_timestamp(s['created']))
  File "/Users/lvh/Code/rackspace/otter/otter/supervisor.py", line 277, in <lambda>
    sorted_servers = sorted(state.active.values(), key=lambda s: from_timestamp(s['created']))
  File "/Users/lvh/Code/rackspace/otter/otter/util/timestamp.py", line 33, in from_timestamp
    return iso8601.parse_date(timestamp)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/iso8601/iso8601.py", line 182, in parse_date
    raise ParseError("Unable to parse date string %r" % datestring)
iso8601.iso8601.ParseError: Unable to parse date string '0001-01-01T00:00:05Z.0001'

otter.test.test_supervisor.FindServersToEvictTests.test_returns_oldest_servers
```

**Comment by manishtomar** [comment]
We don't _really_ support all of ISO8601 as the package is not that reliable. Which is why we decided earlier to remove support for ISO8601 and just talk about that specific format in the [docs](http://docs.rackspace.com/cas/api/v1.0/autoscale-devguide/content/datetimeformat.html). So, I think its ok to update this package as long as it supports that format documented.

**Comment by lvh** [comment]
It's not so much about formatting as it is about which dates are supported. Specifically, the year `0001` is no longer supported in the current version, arguably correctly. We can't update the version, because updating the version makes the tests fail (unless this PR lands).

**Comment by lvh** [comment]
(For more details, see #892.)

**Comment by manishtomar** [comment]
In that case the PR can fix the test by changing the year.

**Comment by lvh** [comment]
Yes, that is what the PR does.

**Comment by manishtomar** [comment]
Oh. I am sorry I didn't notice. The last time I saw it was having only package version change. Thanks for doing this :)
