### ISSUE TITLE
PyOpenSSL can't be upgraded because of missing libffi on jenkins/dev boxes

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#893]
PyOpenSSL is currently stuck at 0.13 because 0.14 uses cryptography which uses cffi/libffi.

**Comment by lvh** [comment]
Reference from rackerlabs/autoscaling-chef#586: this is fixed in Docker, so it's probably easiest to wait until we're all dockerized before tackling this one.

**Comment by cyli** [comment]
This should be fixable now.

**Comment by lvh** [comment]
Tackling this since it is now literally so old that it won't compile against libssls that don't have known security bugs:

```
    static X509_REVOKED * X509_REVOKED_dup(X509_REVOKED *orig) {
    
                          ^
    
    /usr/local/opt/openssl/include/openssl/x509.h:751:15: note: previous declaration is here
    
    X509_REVOKED *X509_REVOKED_dup(X509_REVOKED *rev);
    
                  ^
    
    1 error generated.
    
    error: command 'clang' failed with exit status 1
    
```

**Comment by shangbo** [comment]
@lvh Hi,bro~You can tried to uninstall openssl (command:"brew uninstall openssl") and reinstall pyopenssl==0.13,it works! or you can upgrade pyopenssl.

**Comment by lvh** [comment]
Hi @shangbo -- thanks, but this issue is:

1. resolved;
2. about specific servers for Rackspace Auto Scale.

It always worked fine on my box :)
