### ISSUE TITLE
ServiceRequest and its performer don't allow for using different regions

### ISSUE THREAD

**Issue by radix** [rackerlabs/otter#896]
Right now (actually, not yet in master, but in the concretize-service-request branch) when you create a dispatcher that can support `ServiceRequest`, you specify the region up front. But we have cases where requests to certain services (metrics) need to go to a specific region, which is not the same as the deployment region.

I think there are a couple of options here:

- we could just add a region parameter to ServiceRequest, and have code explicitly provide it when the default is not desired
- we could allow special-casing those specific services (metrics), potentially in a configuration-driven way, e.g. the ServiceRequest performer could look for a region in config['services'][service_name]['region_override'] or something.

**Comment by lvh** [comment]
I think the explicit region is a way better option than adding more stuff to some configuration that probably shouldn't exist in that form in the first place.

**Comment by radix** [comment]
@lvh I think I may have made it sound worse than it would. Think about it this way:

ServiceRequest exposes an interface that lets you talk to services, abstractly. It must rely on being preconfigured to know where those services live (which is how it works now, just like request_func -- when you create the request_func or the performer for a ServiceRequest, you bind a default region).

To maintain this abstraction, we just need to slightly enrich the information about the services that we preconfigure the ServiceRequest performer with. I think most likely this would mean getting rid of the "region" argument, and then extending the "service_mapping" that we pass in so it also includes information about the region of each service, instead of just the name-in-the-catalog like it has today.

The source of this information should likely be the configuration file. Really, it's already in the configuration file; we shouldn't need to change the format of it, though it may be nice to make things more consistent.

I disagree that configuring the regions of services shouldn't be in the configuration. I mean, it's gotta be somewhere, and it certainly shouldn't be hard-coded...

**Comment by radix** [comment]
The main difference between preconfiguring it in the performer and adding a "region" argument to the ServiceRequest is that the latter would allow making requests to the same service on different regions in the same otter process. This isn't a use case we have now, but if we ever do it should be straightforward to add such an argument that overrides the preconfigured regions.

**Comment by lvh** [comment]
Yeah, that was more of an argument against the way the config works than config in general. It's fine if "the region" (e.g. am I part of the LON otter cluster) lives there; it's fine if that gets read and turned into the default region, but I still think the cleanest way to build the ServiceRequest API is to have the region on it, with perhaps the implicit default being "wherever I am deployed right now", because that's the 99% use case.

**Comment by radix** [comment]
I'm still not really happy about passing region to the `ServiceRequest` API for metrics code. Let me try some more advocacy :)

I want the code that makes requests to metrics (which is the odd one out when it comes to the region) to say "Make a request against the configured metrics service", just like everything else says "make a request against the configured cloud servers service". We already have the knowledge in our system to make that a possibility, since we know where each service should be addressed when we're creating the effect dispatcher.

The alternative is passing a `metrics_region` parameter around to anywhere that wants to talk to the metrics service. This conflicts with an overarching goal I've had with a lot of the refactorings I've been working on lately. I'll try to describe that goal in a concise, general way:

*Any Effectful code in Otter should be able to make requests to any service, or perform any other effects supported by Otter's dispatcher, without being special cased, without refactorings-up-the-stack when we introduce such an effect.*

The `request_func` -> `ServiceRequest` factor is a big step in that direction. The `request_func` design meant that effectful code that performed HTTP requests was special -- any function without a `request_func` couldn't make an HTTP request, and to introduce the ability to do an HTTP request we had to figure out some place up the stack where we should create a `request_func` and pass it down to the function, possibly changing several intermediate functions.

Making `region` an argument to `ServiceRequest`, and using it for metrics requests, means that we have to do a similar change -- get the region of the metrics service from the config somewhere up the stack, and pass it explicitly down to any function that wants to make a metrics request.

There's another general programming rule I've been trying to crystallize lately. It's something like:

*Any argument that you take merely to conform to another function's signature, and not because it's a useful dynamicism, is a result of unnecessary complection of concerns.*

I think I still need to work on the precision of that wording. But in this case, I feel like passing the `metrics_region` around qualifies as an unnecessary complection - we *can* get rid of that knowledge from the innermost functions, and I think it's better if we do.

If a case comes up where we need to talk to the same service type on different regions, that would count as a "useful dynamicism", and so the `region` parameter to `ServiceRequest` is warranted.

**Comment by manishtomar** [comment]
How about having `region` in `ServiceRequest` which will be used by the performer only if it is provided? Otherwise, performer's region will be used

**Comment by radix** [comment]
I realize the conversation between @lvh and I on slack a while back has not been recapped here yet.

I think it turned out that I just wasn't explaining the suggestion very well, especially because I didn't make it clear that there is only *one* region we're going to be talking to metrics in -- the point being that we don't actually have a requirement for dynamicism yet.

I *believe* we've both agreed that it'll be fine to get per-service regions from the config file, so that most code won't need to care about regions. The idea is to have something a dict like {ServiceType: {'name': ..., 'region': ...}} in the performer's environment. That dict can be built by a function based on the config. Most services will just use the main configured region, and the metrics service will have its own region as already specified in the config file.


So, because we don't have a requirement for dynamicism yet, we should keep the knowledge of the region away from code trying to make requests to services. As soon as we need to have dynamicism (if ever), we can add a 'region' parameter to ServiceRequest.

**Comment by lvh** [comment]
@radix Thanks for the recap. This was my understanding as well, and I'm reasonably happy with that resolution.

**Comment by radix** [comment]
hm, this isn't actually done.  Did GH automatically close this?

**Comment by radix** [comment]
Fixed by #923.
