### ISSUE TITLE
integration tests on preprod

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#901]
Each PR should get tested against mimic on preprod. This includes creating new schema on each run to ensure that any schema changes work with the code. We can then kill unitgration tests #894.

**Comment by radix** [comment]
The plan for now is:

- [] get update_api_servers.py in autoscaling-chef to support deploying in preprod mode
- [] modify CI job to run update_api_servers.py on preprod and run the mimic-backed integration tests.

**Comment by radix** [comment]
there is a jenkins job (long unused) to deploy to preprod: https://as-jenkins.rax.io/job/littlechef-preprod/

**Comment by manishtomar** [comment]
This is being tracked in https://github.com/rackerlabs/autoscaling-chef/issues/590 instead
