### ISSUE TITLE
Refresh CloudCAFE to latest version and make it work with Jenkins

### ISSUE THREAD

**Issue by sam-falvo** [rackerlabs/otter#913]

**Comment by sam-falvo** [comment]
fyi @shawnashlee -- if you could get in touch with us (or we with you if we start this before you get around to it), that'd be awesome!  Thanks!

**Comment by radix** [comment]
Is this a duplicate of #725?

**Comment by kivattik** [comment]
Yes, I'm closing this since it is effectively duplication of #725.
