### ISSUE TITLE
Metrics should run on convergence tenants

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#931]
Currently metrics collects server data from all tenants. It should have an option to run on certain tenants which mostly will be convergence enabled tenants. It should probably also inject separate metrics for each tenant apart from the total.

**Comment by lvh** [comment]
Why can't we just report metrics when we converge? Converging a bit more often is a good thing, right?

**Comment by manishtomar** [comment]
Yeah. That sounds good. Instead of running as a separate service, metrics can be ingested from convergence.

**Comment by manishtomar** [comment]
I think we should run as separate service until there is proper observer based cycling converger implemented. This lets us measure how well convergence is performing. If for some reason converger is not cycling correctly, then metrics service will capture the deviation. In fact, the same applies when observer is implemented.

**Comment by manishtomar** [comment]
@lvh Any thoughts on above comment?

**Comment by lvh** [comment]
I think it'd be easier to just run convergence a bunch of times. That endpoint needs to work too.
