### ISSUE TITLE
Pick a class attribute documentation standard

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#980]
[Original ask](https://github.com/rackerlabs/otter/pull/975/files#r23710021)

That PR uses [a standard defined by Sphinx](http://sphinx-doc.org/ext/autodoc.html#directive-autoattribute). [This was OK'd by @cyli](https://github.com/rackerlabs/otter/pull/975#issuecomment-71769198). @radix suggests [a different standard defined by Sphinx](http://sphinx-doc.org/domains.html#info-field-lists).

**Comment by radix** [comment]
I had no idea docstring-under-attribute was supported by sphinx. Given that it is, I think it's fine. :)

**Comment by lvh** [comment]
Oh, okay. So, closing as invalid?
