### ISSUE TITLE
Rename `has_code` to `has_codes`

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#983]
Predicate function `has_code` takes multiple codes as argument. It would be better to rename it to `has_codes`.

**Comment by lvh** [comment]
FWIW, I disagree unless the signature becomes a sequence of codes, because otherwise you just make `has_code(200)` look really weird. I read just `has_code(200, 409)` as `has_code 200 or 409`, and that makes English grammatical sense to me.

**Comment by manishtomar** [comment]
I see your point w.r.t making English grammatical sense. Closing
