### ISSUE TITLE
 Getting group status should reflect changes in Convergence for whitelisted tenants

### ISSUE THREAD

**Issue by radix** [rackerlabs/otter#985]
There are a couple of options here.

1. Getting group status, for convergence-enabled customers, shouldn't show 'active' or 'pending', just 'desired', since we don't keep track of that information any more.
2. Getting group status for convergence-enabled customers should make a request to nova to determine the active/pending servers. This would maintain backwards compatibility but could be a major stress to Nova since we have to scan the entire server list every time a group is fetched.

**Comment by wirehead** [comment]
So... 1 represents a bit of a problem because we're changing the API.
2 may or may not get us in deep trouble with Nova.

For the purposes of simplicity, I think we can just display the state, as we know it, from the last time we tried to run converge.

**Comment by manishtomar** [comment]
> For the purposes of simplicity, I think we can just display the state, as we know it, from the last time we tried to run converge.

+1

**Comment by radix** [comment]
Ok, so it looks like this has been decided, this ticket will now be used to track the implementation progress.

**Comment by cyli** [comment]
Just for clarification, this state cache is going to be stored in Cassandra?

**Comment by radix** [comment]
Yes, it'll just store the active and pending servers into cassandra in the same way they're stored now.
