### ISSUE TITLE
Decide if an inactive/missing RCv3 load balancer warrants ERROR condition

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#987]
This came up in resolving #820.

**Comment by wirehead** [comment]
LVH asked additional prompting questions -- we're going to replace old machines with their old launch config.  This means that if we're trying to scale up, an inactive or missing RCv3 LB should cause an ERROR condition.

**Comment by lvh** [comment]
Thanks, @wirehead! Assigning this to myself so I can implement it :)

**Comment by cyli** [comment]
@wirehead Can you please clarify the statement "we're going to replace old machines with their old launch config"?

**Comment by wirehead** [comment]
New servers, as in when you scale-up, are going to be launched with the newest launch config.  Same as always.

In the case where a server goes into an error state or otherwise disappears/goes bad, we're going to re-provision it with its old launch config, assuming we can.

**Comment by cyli** [comment]
This seems doable with regular servers, but seems like a huge amount more work for BFV servers.  Is this a requirement for milestone 3?

**Comment by cyli** [comment]
@wirehead What about servers deleted out of band?  Should they be replaced with their original configuration?

**Comment by cyli** [comment]
Actually, let me move this to a new issue.

**Comment by lvh** [comment]
This has been resolved in master.
