### ISSUE TITLE
Fix CLB bulk APIs

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#989]
Fix CLB bulk APIs:

- [x] The AddNodesToCLB url is wrong, and also succeed on 413 because we want to just try again next convergence cycle.  Ditto with 422 in the case of duplicate nodes.
- [x] There is a bulk delete nodes API on CLB - add that one.
    - The URL is wrong - it is missing 'nodes' between the load balancer ID and the node ID
    - Try again on 413, 422 PENDING_UPDATE, and succeed on load balancers being deleted
- [ ] Optimize the bulk delete calls

### ORIGINAL DESCRIPTION:  

[The documentation](http://docs.rackspace.com/loadbalancers/api/v1.0/clb-devguide/content/Nodes-d1e2173.html) does not mention [the API we appear to use in convergence](https://github.com/rackerlabs/otter/blob/master/otter/convergence/steps.py#L114-L122), so I'm not sure it's correct.

**Comment by lvh** [comment]
@cyli and I just walked through the documentation and are now convinced it's not correct, so I guess we get to replace that with a step that does actually map to an API call?

**Comment by cyli** [comment]
Ok, the documentation says "Add Node", but the example json contains 3 nodes.  So it's not super clear - going to test this out and see what it actually does.

**Comment by cyli** [comment]
Tested it - adding multiple nodes does work.

**Comment by cyli** [comment]
Actually the URL is wrong - it needs to go to `/loadbalancers/lbid/nodes`, but that I think is the only issue.

**Comment by cyli** [comment]
Also, CLB has bulk delete operations.  Going to change the title and description of this issue.
